"""Entire native5392-byte tooltip error independently reproduced without mods."""
import hashlib,json,logging,re,shutil,sys,zipfile
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime','--vanilla'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name)
prod=Path(json.loads(Path(m['production_pointer_backup']).read_text('utf-8'))['artifact_dir']);pp=json.loads((prod/'terravore-native-stage3-ack-2780-tooltip-notice-proof.json').read_text('utf-8'));pe=json.loads((prod/'terravore-native-stage3-ack-guard-execution.json').read_text('utf-8'));pre=json.loads((run/'shroud2780-control-loaded-supplement.json').read_text('utf-8'));obs=json.loads((run/'shroud2780-control-hover-observation.json').read_text('utf-8'))
pb=(prod/'terravore-native-stage3-pending-error-after.log').read_bytes();pa=(prod/'terravore-native-stage3-ack-error-before.log').read_bytes();cb=(run/'shroud2780-control-hover-error-before.log').read_bytes();ca=(run/'shroud2780-control-hover-error-after.log').read_bytes();pd,cd=pa[len(pb):],ca[len(cb):];norm=lambda v:re.sub(rb'\[\d{2}:\d{2}:\d{2}\]',b'[TIME]',v)
checks={
 'actual_empty_mod_configuration':m['enabled_mods']==[] and json.loads((user/'dlc_load.json').read_text('utf-8'))=={'enabled_mods':[],'disabled_dlcs':[]},
 'production28_exact_only_error_FAIL_exit1':pp['status']=='FAIL' and len(pp['checks'])==28 and {k for k,v in pp['checks'].items() if not v}=={'unfiltered_error_zero_increment'} and pe['returncode']==1,
 'other27_production_raw_checks_true':all(v is True for k,v in pp['checks'].items() if k!='unfiltered_error_zero_increment'),
 'original_production_SHA_pair':h.sha256(prod/'terravore-native-stage3-pending.sav')==pp['before_sha256']==m['original_seed']['sha256'] and h.sha256(prod/'terravore-native-stage3-ack.sav')==pp['after_sha256'],
 'control6_load_supplement_PASS_exit0':pre['status']=='PASS_NATIVE2780_CONTROL_LOAD_SUPPLEMENT' and len(pre['checks'])==6 and all(v is True for v in pre['checks'].values()) and json.loads((run/'shroud2780-control-load-supplement-execution.json').read_text('utf-8'))['returncode']==0,
 'same_original_byte_alias_loaded':h.sha256(Path(m['original_seed']['alias']))==pp['before_sha256']==pre['before_sha256'],
 'native_hover_only_actual_exit0':json.loads((run/'shroud2780-control-hover-observe-execution.json').read_text('utf-8'))['returncode']==0 and json.loads((run/'shroud2780-control-hover-option-hover.action.json').read_text('utf-8'))['clicks']==0,
 'exact_same_control_SAV_before_after':h.sha256(run/'shroud2780-control-loaded.sav')==h.sha256(run/'shroud2780-control-hover.sav')==pre['after_sha256']==obs['before_sha256']==obs['after_sha256'],
 'error_prefixes_held_separate_load_baseline':ca.startswith(cb) and pa.startswith(pb) and cb==(run/'shroud2780-load-error-after.log').read_bytes() and len(cb)==4632 and (prod/'terravore-native-stage3-ack-error-after.log').read_bytes()==pa,
 'exact5392_increment_both':len(pd)==len(cd)==obs['new_error_bytes']==5392,
 'entire_error_body_equal_timestamp_only':norm(pd)==norm(cd),
 'exact_seven_native_error_sites':len(re.findall(rb'\[\d{2}:\d{2}:\d{2}\]\[[^\]]+\]:',cd))==7 and cd.count(b'Wrong scope for trigger')==5 and cd.count(b'Invalid context switch [founder_species]')==2 and all(b'common/scripted_loc/13_scripted_loc_shroud.txt line: '+str(n).encode() in cd for n in [2673,2680,2688,2696,2703,2704,2705]),
}
game=h.GAME_EXE.parent;source=game/'events/shroud_situation_events.txt';loc=game/'common/scripted_loc/13_scripted_loc_shroud.txt';trad=game/'localisation/simp_chinese/traditions_l_simp_chinese.yml';shloc=game/'localisation/simp_chinese/shroud_l_simp_chinese.yml';trigger=game/'common/scripted_triggers/00_scripted_triggers.txt';machine=game/'common/scripted_triggers/02_scripted_triggers_machine_age.txt'
ev=[v for k,v,o in q.fields(source.read_text('utf-8-sig')) if o and q.scalars(v).get('id')=='shroud.2780'];assert len(ev)==1
checks['native_tooltip_reference_source_chain']=q.scalars(q.block(q.block(ev[0],'option'),'if')).get('custom_tooltip')=='shroud.2780.a_tt_trad' and 'shroud.2780.a_tt_trad: "$tr_psionics_psionic_assimilation_desc$' in shloc.read_text('utf-8-sig') and '[GetPsionicAssimilationEffectShroud]' in next(line for line in trad.read_text('utf-8-sig').splitlines() if 'tr_psionics_psionic_assimilation_desc:' in line) and 'name = GetPsionicAssimilationEffectShroud' in loc.read_text('utf-8-sig')
checks['Mod_does_not_define_native_function']=not any('GetPsionicAssimilationEffectShroud' in p.read_text('utf-8-sig') for p in h.MOD_ROOT.rglob('*.txt'))
p={'status':'PASS_SCOPED_NO_MOD_NATIVE2780_TOOLTIP_ERROR' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':pre['after_sha256'],'after_sha256':obs['after_sha256'],'production_before_after_sha256':[pp['before_sha256'],pp['after_sha256']],'production_error_sha256':hashlib.sha256(pd).hexdigest(),'control_error_sha256':hashlib.sha256(cd).hexdigest(),'error_increment_bytes':len(cd),'native_sources':[{'path':str(v),'sha256':h.sha256(v)} for v in [source,loc,trad,shloc,trigger,machine]],'scope':'Same complete5392-byte native tooltip error reproduced by ordinary hover with enabled_mods empty; only timestamp differs. Mod-derived world, missing-origin load baseline separate. Not pure vanilla generation, internal engine root cause or original no-error PASS.'};out=run/'shroud2780-control-error-proof.json';assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original native tooltip control FAIL retained'
