"""Join actual production20 valid checks and exact no-mod native error control."""
import json,logging,re,shutil,sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();assert m['enabled_mods']==['mod/ugc_eep-local.mod'];shutil.copyfile(__file__,run/Path(__file__).name)
control=Path('eat_everything_origin/docs/evidence/priority-terravore-progress-2026-10-09/native-coordinator-capital-payment-error-control');read=lambda p:json.loads(p.read_text('utf-8'));st='terravore-ascension-capital-paid';orig=read(run/(st+'-capital-payment-proof.json'));cp=read(control/'coordinator-control-paid-error-proof.json')
pb=(run/(st+'-error-before.log')).read_bytes();pa=(run/(st+'-error-after.log')).read_bytes();cb=(control/'coordinator-control-paid-error-before.log').read_bytes();ca=(control/'coordinator-control-paid-error-after.log').read_bytes();pd,cd=pa[len(pb):],ca[len(cb):];norm=lambda v:re.sub(rb'\[\d{2}:\d{2}:\d{2}\]',b'[TIME]',v)
checks={'original30_exact_only_error_FAIL_other29_true':orig['status']=='FAIL' and len(orig['checks'])==30 and [k for k,v in orig['checks'].items() if not v]==['unfiltered_error_original_bytes_held'],'original_guard_execution1_save_execution0':read(run/(st+'-guard-execution.json'))['returncode']==1 and read(run/(st+'-save-execution.json'))['returncode']==0,'production_original_SHA_pair':h.sha256(run/'terravore-ascension-generator5-month.sav')==orig['before_sha256'] and h.sha256(run/(st+'.sav'))==orig['after_sha256'],'bound_control33_PASS_actual_execution_zero':cp['status']=='PASS_SCOPED_NO_MOD_NATIVE_COORDINATOR_ERROR' and len(cp['checks'])==33 and all(cp['checks'].values()) and read(control/'coordinator-control-error-guard-execution.json')['returncode']==0,'control_original_SHA_pair':h.sha256(control/'coordinator-control-hover.sav')==cp['before_sha256'] and h.sha256(control/'coordinator-control-paid.sav')==cp['after_sha256'],'control_actual_enabled_mods_empty':read(control/'userdir-config/dlc_load.json')=={'enabled_mods':[],'disabled_dlcs':[]},'all_original_error_prefixes_preserved':pa.startswith(pb) and ca.startswith(cb),'same_exact255_error_after_timestamp_only_normalization':len(pd)==len(cd)==255 and norm(pd)==norm(cd),'one_exact_native_coordinator_context_error':pd.count(b'Script Error:')==1 and b'common/pop_jobs/04_gestalt_jobs.txt line: 562' in pd and b'id=4294967295' in pd,'all_native_source_SHA_held':h.sha256(Path(cp['native_source']['path']))==cp['native_source']['sha256']=='9469c178efbaa2d8e5bce43545ee6d5a184ee0e764336e85170795d0cc6820ad','production_package_unchanged':h.tree_manifest(h.MOD_ROOT)[1]=='ac802ed0b6226731b039458a472f46ed5c6f7f7de3e629751509cbb322f9eae7'}
p={'status':'PASS_SCOPED_NATIVE_COORDINATOR_ERROR_ATTRIBUTION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':orig['before_sha256'],'after_sha256':orig['after_sha256'],'frozen_control_checkpoint':str(control),'unfiltered_error_lengths_before_after':[len(pb),len(pa)],'scope':'29 valid production payment checks joined with exact255-byte native coordinator error reproduced by normal480-mineral upgrade with empty enabled_mods. Original strict30 no-new-error FAIL retained; no internal root-cause, pure vanilla-generation or full-route claim.'};out=run/(st+'-native-coordinator-error-supplement.json');assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original scoped supplement FAIL retained'
