"""Independent scoped attribution of original yearly error; no original proof rewrite."""
import json,logging,re,shutil,sys,zipfile
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(Path(__file__),run/Path(__file__).name)
control=Path('eat_everything_origin/docs/evidence/priority-terravore-progress-2026-10-09/native-preftl-error-control')
def read(p):return json.loads(p.read_text('utf-8'))
year=read(run/'terravore-second-psionic-wait-year1-second-psionic-wait-proof.json');err=read(control/'preftl-control-error-reproduction-proof.json');pop=read(control/'preftl-control-population-supplement.json');sup=read(control/'preftl-control-growth-pairs-supplement.json')
def native(stem):
 with zipfile.ZipFile(run/(stem+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 roots={k:v for k,v,o in q.fields(t) if o};c=q.block(roots['country'],'29');cs=q.scalars(c);col=q.block(roots['colony'],str(cs['capital']));carrier=q.scalars(q.block(col,'carrier'));ps=q.scalars(q.block(q.block(roots['planets'],'planet'),str(carrier['reference'])));groups=[q.scalars(q.block(roots['pop_groups'],str(i))) for i in q.ids(q.block(col,'pop_groups'))]
 return c,cs,ps,groups
b,bs,bp,bg=native('terravore-second-postsettlement-month');a,as_,ap,ag=native('terravore-second-psionic-wait-year1');pb=(run/'terravore-second-psionic-wait-year1-error-before.log').read_bytes();pa=(run/'terravore-second-psionic-wait-year1-error-after.log').read_bytes();cb=(control/'preftl-control-event-error-before.log').read_bytes();ca=(control/'preftl-control-event-error-after.log').read_bytes();pd,cd=pa[len(pb):],ca[len(cb):];norm=lambda v:re.sub(rb'\[\d{2}:\d{2}:\d{2}\]',b'[TIME]',v)
checks={'bound_original_year25_only_error_FAIL_other24_true':year['status']=='FAIL' and len(year['checks'])==25 and [k for k,v in year['checks'].items() if not v]==['no_new_error'], 'original_year_SHA_pair':h.sha256(run/'terravore-second-postsettlement-month.sav')==year['before_sha256'] and h.sha256(run/'terravore-second-psionic-wait-year1.sav')==year['after_sha256'], 'bound_control5_actual_PASS':sup['status']=='PASS_SCOPED_NO_MOD_PRE_FTL_REPRODUCTION_SUPPLEMENT' and len(sup['checks'])==5 and all(sup['checks'].values()), 'bound_control15_error_and8_population_valid':err['status']==pop['status']=='FAIL' and len(err['checks'])==16 and [k for k,v in err['checks'].items() if not v]==['target29_native_population200_to300'] and len(pop['checks'])==9 and [k for k,v in pop['checks'].items() if not v]==['native_colony_OTHER100_observed'], 'control_all_three_SHA_pairs_same':err['before_sha256']==pop['before_sha256']==sup['before_sha256']==h.sha256(control/'preftl-control-loaded.sav') and err['after_sha256']==pop['after_sha256']==sup['after_sha256']==h.sha256(control/'preftl-control-event.sav'), 'control_actual_enabled_mods_empty':read(control/'userdir-config/dlc_load.json')['enabled_mods']==[], 'all_original_error_prefixes_preserved':pa.startswith(pb) and ca.startswith(cb), 'same_exact972_native_error_after_timestamp_only_normalization':len(pd)==len(cd)==972 and norm(pd)==norm(cd), 'production_native_country29_primitive_stone_to_bronze':bs['type']==as_['type']=='primitive' and bs['preftl_age']=='stone_age' and as_['preftl_age']=='bronze_age', 'production_Col8_physical1485_owner29_actual200_to300':bs['capital']==as_['capital']==8 and bp['colony']==ap['colony']==8 and bp['owner']==ap['owner']==bp['controller']==ap['controller']==29 and sum(g['size'] for g in bg)==200 and sum(g['size'] for g in ag)==300 and all(g['planet']==8 for g in [*bg,*ag]), 'production_original_government_raw_held':q.block(b,'government')==q.block(a,'government'), 'target29_not_EEP_qualified':q.scalars(q.block(a,'government'))['origin']=='origin_post_apocalyptic' and not any(c in q.block(a,'government') for c in ['civic_hive_devouring_swarm','civic_machine_terminator','civic_fanatic_purifiers','civic_scorched_earth','civic_hive_scorched_earth'])}
p={'status':'PASS_SCOPED_NATIVE_PRE_FTL_ERROR_ATTRIBUTION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':year['before_sha256'],'after_sha256':year['after_sha256'],'original_year_proof':'terravore-second-psionic-wait-year1-second-psionic-wait-proof.json','committed_control_checkpoint':str(control),'unfiltered_error_lengths_before_after':[len(pb),len(pa)],'scope':'Original yearly24 valid checks joined with same exact native972 error independently reproduced with no enabled mods and unchanged native target29 government. Original no-new-error FAIL retained; no clean vanilla generation/root-cause, load-baseline certification, long-term or full route pass.'}
out=run/'terravore-second-psionic-wait-year1-native-preftl-error-supplement.json';assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original error attribution supplement FAIL retained'
