"""Join actual production20 valid checks and exact no-mod native error control."""
import json,logging,re,shutil,sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();assert m['enabled_mods']==['mod/ugc_eep-local.mod'];shutil.copyfile(__file__,run/Path(__file__).name)
control=Path('eat_everything_origin/docs/evidence/priority-terravore-progress-2026-10-09/native-leader-trait-error-control');read=lambda p:json.loads(p.read_text('utf-8'));st='terravore-defense-post-battle-repair-month';orig=read(run/(st+'-native-combat-boundary-proof.json'));cp=read(control/'leader13-control-fleet-error-reproduction-proof.json')
pb=(run/(st+'-error-before.log')).read_bytes();pa=(run/(st+'-error-after.log')).read_bytes();cb=(control/'leader13-control-fleet-effect-error-before.log').read_bytes();ca=(control/'leader13-control-fleet-effect-error-after.log').read_bytes();pd,cd=pa[len(pb):],ca[len(cb):];norm=lambda v:re.sub(rb'\[\d{2}:\d{2}:\d{2}\]',b'[TIME]',v)
checks={'original21_exact_only_error_FAIL_other20_true':orig['status']=='FAIL' and len(orig['checks'])==21 and [k for k,v in orig['checks'].items() if not v]==['unfiltered_error_bytes_held'],'original_guard_execution1_calendar_execution0':read(run/(st+'-guard-execution.json'))['returncode']==1 and read(run/(st+'-observe-execution.json'))['returncode']==0,'production_original_SHA_pair':h.sha256(run/'terravore-defense-merged-return-ordered.sav')==orig['before_sha256'] and h.sha256(run/(st+'.sav'))==orig['after_sha256'],'bound_control14_PASS_actual_execution_zero':cp['status']=='PASS_SCOPED_NO_MOD_LEADER13_ERROR_REPRODUCTION' and len(cp['checks'])==14 and all(cp['checks'].values()) and read(control/'leader13-control-fleet-error-guard-execution.json')['returncode']==0,'control_original_SHA_pair':h.sha256(control/'leader13-control-event.sav')==cp['before_sha256'] and h.sha256(control/'leader13-control-fleet-effect.sav')==cp['after_sha256'],'control_actual_enabled_mods_empty':read(control/'userdir-config/dlc_load.json')=={'enabled_mods':[],'disabled_dlcs':[]},'all_original_error_prefixes_preserved':pa.startswith(pb) and ca.startswith(cb),'same_exact144_error_after_timestamp_only_normalization':len(pd)==len(cd)==144 and norm(pd)==norm(cd),'one_exact_native_leader13_trait_rejection':pd.count(b'councilor_trait_not_allowed')==1 and b'events/leader_events_1.txt line: 683' in pd,'all_native_source_SHA_held':all(h.sha256(Path(s['path']))==s['sha256'] for s in cp['native_sources']),'production_package_unchanged':h.tree_manifest(h.MOD_ROOT)[1]=='ac802ed0b6226731b039458a472f46ed5c6f7f7de3e629751509cbb322f9eae7'}
p={'status':'PASS_SCOPED_NATIVE_LEADER13_ERROR_ATTRIBUTION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':orig['before_sha256'],'after_sha256':orig['after_sha256'],'committed_control_checkpoint':str(control),'unfiltered_error_lengths_before_after':[len(pb),len(pa)],'scope':'20 valid production component checks joined with same complete144-byte native leader.13 error independently reproduced with empty enabled_mods. Original strict21 no-new-error FAIL retained; no identification of natural offender, vanilla-origin generation or full-route acceptance.'};out=run/(st+'-native-leader13-error-supplement.json');assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original scoped supplement FAIL retained'
