"""Exact paused native purchase for founder colony523, no calendar or grants."""
import json,logging,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime']
import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,meta=h.load_run()
dest=run/Path(__file__).name
if dest.exists():assert dest.read_bytes()==Path(__file__).read_bytes()
else:shutil.copyfile(__file__,dest)
load=lambda name:json.loads((run/name).read_text('utf-8'))
before='terravore-war1-idle22-step1';after='terravore-yomon-colony-paid'
def read(st):
 with zipfile.ZipFile(run/(st+'.sav')) as z:fs=list(q.fields(z.read('gamestate').decode('utf-8-sig')))
 return load(st+'.audit.json'),fs,{k:v for k,v,o in fs if o}
def omit(t,ks):return [(k,v,o) for k,v,o in q.fields(t) if k not in ks]
def tok(t):return [v for v,x,y in q.tokens(t)]
def single(t):
 ts=list(q.tokens(t));assert ts[0][0]=='{' and ts[-1][0]=='}';return t[ts[0][2]:ts[-1][1]]
b,bf,br=read(before);a,af,ar=read(after);bc,ac=b['countries']['0'],a['countries']['0']
pre=load(before+'-war1-battle-v32-proof.json');ex=load(before+'-battle-v32-execution.json')
cb,ca=[q.block(t['country'],'0') for t in [br,ar]];mb,ma=[q.block(t,'modules') for t in [cb,ca]];eb,ea=[q.block(t,'standard_economy_module') for t in [mb,ma]];rb,ra=[q.block(t,'resources') for t in [eb,ea]];xb,xa=[q.block(t,'standard_expansion_module') for t in [mb,ma]];exp=single(q.block(xa,'expansion_list'))
bcon,acon=br['construction'],ar['construction'];bqm,aqm=[q.block(t,'queue_mgr') for t in [bcon,acon]];bqs,aqs=[q.block(t,'queues') for t in [bqm,aqm]];bim,aim=[q.block(t,'item_mgr') for t in [bcon,acon]];bi,ai=[q.block(t,'items') for t in [bim,aim]];bq,aq=[q.block(t,'3') for t in [bqs,aqs]];item=q.block(ai,'16777256');col=q.block(item,'buildable_colony_ship');design={'design':150995039,'upgrade':4294967295,'growth_stage':0}
fb,fa=[q.block(t['fleet'],'715') for t in [br,ar]]
budget=load('terravore-three-mines-budget-cycle-proof.json');budgetex=load('terravore-three-mines-budget-cycle-guard-execution.json')
checks={
 'production02_Chinese_exact_same_date_SHA_pair':meta['version']=='0.2.0' and meta['language']=='l_simp_chinese' and b['date']==a['date']=='2270.05.15' and b['save_sha256']==h.sha256(run/(before+'.sav'))=='359451ce1ca32684e54c78ab7288de105360db23e1317e7ba718d9d7b59ca930' and a['save_sha256']==h.sha256(run/(after+'.sav'))=='a416d360d40d28b24e2a8fc9d01b0c279bf03fd1bd24dd52c77b5c136415c9b0',
 'prior50_PASS_actual0_original_V32_bound':pre['status']=='PASS_TERRAVORE_NATIVE_WAR1_POSTBATTLE_MIA_OBSERVATION_COMPONENT' and len(pre['checks'])==50 and all(v is True for v in pre['checks'].values()) and pre['after_sha256']==b['save_sha256'] and ex['returncode']==0 and ex['helper_sha256']==h.sha256(run/'priority_terravore_war1_battle_observer_v32.py')=='01747d1c4dc472f10f46cf644492cf4ea705252a13d887902c38624c62603f57',
 'budget16_PASS_actual0_source_bound':len(budget['checks'])==16 and all(v is True for v in budget['checks'].values()) and budgetex['returncode']==0 and budgetex['helper_sha256']==h.sha256(run/'priority_terravore_three_mines_budget_cycle_guard.py')=='ea97e0817620d7be0cad18ea4b9818e7ba71cfae3670646ba5a81c5f5c1f377f',
 'only375_minerals150_alloys_paid_all_true_banks_held':D(str(bc['effective_stockpile']['minerals']))-D(str(ac['effective_stockpile']['minerals']))==375 and D(str(bc['effective_stockpile']['alloys']))-D(str(ac['effective_stockpile']['alloys']))==150 and {k:v for k,v in bc['effective_stockpile'].items() if k not in {'minerals','alloys'}}=={k:v for k,v in ac['effective_stockpile'].items() if k not in {'minerals','alloys'}} and bc['research_stockpile']==ac['research_stockpile'],
 'exact_native_research_display_mirror_refresh_only':omit(rb,{'minerals','alloys',*q.RESEARCH_RESOURCES})==omit(ra,{'minerals','alloys',*q.RESEARCH_RESOURCES}) and {k:q.scalars(rb).get(k) for k in q.RESEARCH_RESOURCES}=={'physics_research':29.2595,'society_research':6588.75766,'engineering_research':30.8095} and {k:q.scalars(ra).get(k) for k in q.RESEARCH_RESOURCES}=={'physics_research':None,'society_research':6597.39029,'engineering_research':None},
 'country0_only_economy_resources_and_expansion_changed':omit(br['country'],{'0'})==omit(ar['country'],{'0'}) and omit(cb,{'modules'})==omit(ca,{'modules'}) and omit(mb,{'standard_economy_module','standard_expansion_module'})==omit(ma,{'standard_economy_module','standard_expansion_module'}) and omit(eb,{'resources'})==omit(ea,{'resources'}),
 'one_expansion523_added_exact_schema':not xb.strip() and omit(xa,{'expansion_list'})==[] and q.scalars(exp)=={'target_planet':523,'construction_queue':3,'construction_queue_item':16777256} and [(k,o) for k,v,o in q.fields(exp)]==[('colonization_data',True),('ship_design_implementation',True),('target_planet',False),('construction_queue',False),('construction_queue_item',False),('name',True)],
 'founder73_original_design_exact_default_name_Yomon':q.scalars(q.block(exp,'colonization_data'))=={'species':73} and q.scalars(q.block(exp,'ship_design_implementation'))==design and tok(q.block(exp,'name'))==['key','=','"NEW_COLONY_NAME_1"','variables','=','{','{','key','=','"NAME"','value','=','{','key','=','"Yomon"','}','}','}'],
 'only_queue3_new_colony_order_appended':not q.block(bq,'items').strip() and q.ids(q.block(aq,'items'))==[16777256] and omit(bq,{'items'})==omit(aq,{'items'}) and q.scalars(aq)=={'owner':0,'simultaneous':2,'type':'ships'} and q.scalars(q.block(aq,'location'))=={'type':0,'id':0} and omit(bqs,{'3'})==omit(aqs,{'3'}),
 'one360_work_colony_order_paid0_progress':q.scalars(item)=={'queue':3,'paying_country':0,'progress':0,'progress_needed':360} and q.scalars(q.block(item,'resources'))=={'minerals':375,'alloys':150} and q.scalars(q.block(col,'ship_design_implementation'))==design and q.scalars(q.block(col,'orbitable'))=={'starbase':0} and q.scalars(q.block(col,'colonization_data'))=={'species':73} and [(k,o) for k,v,o in q.fields(item)]==[('queue',False),('paying_country',False),('progress',False),('progress_needed',False),('resources',True),('buildable_colony_ship',True)],
 'exact_none40_handle_generation_reused_all_other_items_held':[(k,v,o) for k,v,o in q.fields(bi) if k=='40']==[('40','none',False)] and not any(k=='40' for k,v,o in q.fields(ai)) and not any(k=='16777256' for k,v,o in q.fields(bi)) and omit(bi,{'40'})==omit(ai,{'16777256'}) and 16777256-40==16777216,
 'construction_other_manager_fields_held':omit(bcon,{'queue_mgr','item_mgr'})==omit(acon,{'queue_mgr','item_mgr'}) and omit(bqm,{'queues'})==omit(aqm,{'queues'}) and omit(bim,{'items'})==omit(aim,{'items'}),
 'one_civilian715_exact_native_dirty_flag_only':omit(br['fleet'],{'715'})==omit(ar['fleet'],{'715'}) and omit(fb,{'properties'})==omit(fa,{'properties'}) and list(q.fields(q.block(fa,'properties')))==list(q.fields(q.block(fb,'properties')))+[('dirty_cloaking_strength','yes',False)] and q.scalars(q.block(fb,'properties'))=={'civilian':'yes','mobile':'yes','valid_for_combat':'yes','can_construct_megastructures':'yes'},
 'all_other_ordered_top_raw_held_no_ship_or_planet_change':[(k,v,o) for k,v,o in bf if k not in {'country','construction','fleet'}]==[(k,v,o) for k,v,o in af if k not in {'country','construction','fleet'}],
 'normal_order_click_name_confirm_and_native_save_actual0':all(load(st+'-execution.json')['returncode']==0 for st in ['terravore-yomon-colony-order-click','terravore-yomon-colony-name-confirm',after+'-native-save']) and all(load(st+'-execution.json')['helper_sha256']==h.sha256(run/'priority_native_ui_input_v3.py')=='801941d04cb3b4434483d22f3418187438142d66c9740367794ae75f2ac41a9f' for st in ['terravore-yomon-colony-order-click','terravore-yomon-colony-name-confirm']) and load('terravore-yomon-colony-order-click.action.json')['client_point']==[803,604] and load('terravore-yomon-colony-name-confirm.action.json')['client_point']==[590,420] and load(after+'-native-save-execution.json')['helper_sha256']==h.sha256(run/'priority_native_save.py')=='19fea261969af27e547860acead4fa010e90612d8b6d2904b1b6b11ba49ee82e',
 'actual_375M150A_quote_original_image_bound':h.sha256(run/'terravore-yomon-colony-species-quote-visible.jpg')==load('terravore-yomon-colony-species-quote-visible.ocr.json')['image_sha256']=='ca481ce143f4d211e1ef6aafb7b05c0321094d599c8a849ced9f26934c35235b',
 'no_country0_pending_and_2814_unfiltered_error_exact_held':not[v for k,v,o in af if k=='player_event' and o and q.scalars(v).get('country')==0] and (run/(before+'-error-after.log')).read_bytes()==(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes() and h.sha256(run/(after+'-error-after.log'))=='df43a78778ff981c9add0382adb3fd127128adbc6006d6bfd7db6a194c6056eb',
}
proof={k:v for k,v in pre.items() if k not in {'status','checks','before_sha256','after_sha256','days','scope'}}
proof.update(status='PASS_TERRAVORE_YOMON_COLONY_PAYMENT_COMPONENT' if all(checks.values()) else 'FAIL',checks=checks,before_sha256=b['save_sha256'],after_sha256=a['save_sha256'],date=a['date'],actual_stockpiles=ac['effective_stockpile'],actual_colony523_order_id=16777256,actual_colony523_order_raw=item,actual_colony523_expansion_raw=exp,actual_colony523_order_progress=0,calendar_ready=all(checks.values()),short_idle_war_calendar_ready=all(checks.values()),scope='One actual paid colony523 order only, no completion, transit, colony or EEP reward.')
out=run/(after+'-colony-payment-proof.json');assert not out.exists();h.write_json(out,proof);print(json.dumps({'status':proof['status'],'checks':len(checks),'failed':[k for k,v in checks.items() if v is not True]}),flush=True);assert all(checks.values()),'Original purchase evidence retained; never repeat purchase'
