"""Exact same-day native heavy-industry conversion purchase, before work."""
import json,logging,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime']
import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,meta=h.load_run();dest=run/Path(__file__).name
if dest.exists():assert dest.read_bytes()==Path(__file__).read_bytes()
else:shutil.copyfile(__file__,dest)
load=lambda name:json.loads((run/name).read_text('utf-8'))
before='terravore-yomon-colony-paid';after='terravore-mother-heavy-conversion-paid'
def read(st):
 with zipfile.ZipFile(run/(st+'.sav')) as z:fs=list(q.fields(z.read('gamestate').decode('utf-8-sig')))
 return load(st+'.audit.json'),fs,{k:v for k,v,o in fs if o}
def omit(t,ks):return [(k,v,o) for k,v,o in q.fields(t) if k not in ks]
b,bf,br=read(before);a,af,ar=read(after);bc,ac=b['countries']['0'],a['countries']['0'];pre=load(before+'-colony-payment-proof.json');ex=load(before+'-guard-execution.json')
cb,ca=[q.block(t['country'],'0') for t in [br,ar]];mb,ma=[q.block(t,'modules') for t in [cb,ca]];eb,ea=[q.block(t,'standard_economy_module') for t in [mb,ma]];rb,ra=[q.block(t,'resources') for t in [eb,ea]]
bcon,acon=br['construction'],ar['construction'];bqm,aqm=[q.block(t,'queue_mgr') for t in [bcon,acon]];bqs,aqs=[q.block(t,'queues') for t in [bqm,aqm]];bim,aim=[q.block(t,'item_mgr') for t in [bcon,acon]];bi,ai=[q.block(t,'items') for t in [bim,aim]];bq,aq=[q.block(t,'0') for t in [bqs,aqs]];item=q.block(ai,'16777257')
checks={
 'production02_Chinese_same_date_exact_SHA_pair':meta['version']=='0.2.0' and meta['language']=='l_simp_chinese' and b['date']==a['date']=='2270.05.15' and b['save_sha256']==h.sha256(run/(before+'.sav'))=='a416d360d40d28b24e2a8fc9d01b0c279bf03fd1bd24dd52c77b5c136415c9b0' and a['save_sha256']==h.sha256(run/(after+'.sav'))=='d7ecdd864e0b97bbca18f6d2ad6cd1c7af871191770e558dc6fe3abc5495a732',
 'prior_colony17_PASS_actual0_fixed_source_bound':pre['status']=='PASS_TERRAVORE_YOMON_COLONY_PAYMENT_COMPONENT' and len(pre['checks'])==17 and all(v is True for v in pre['checks'].values()) and pre['after_sha256']==b['save_sha256'] and ex['returncode']==0 and ex['helper_sha256']==h.sha256(run/'priority_terravore_yomon_colony_payment_guard.py')=='1d8279c62e72e4033cbb1b32332ffac84db0b3bd8c164b1b12c516facaefe24a',
 'only800_minerals_paid_all_other_true_banks_held':D(str(bc['effective_stockpile']['minerals']))-D(str(ac['effective_stockpile']['minerals']))==800 and {k:v for k,v in bc['effective_stockpile'].items() if k!='minerals'}=={k:v for k,v in ac['effective_stockpile'].items() if k!='minerals'} and bc['research_stockpile']==ac['research_stockpile'],
 'country0_only_economy_minerals_raw_changed':omit(br['country'],{'0'})==omit(ar['country'],{'0'}) and omit(cb,{'modules'})==omit(ca,{'modules'}) and omit(mb,{'standard_economy_module'})==omit(ma,{'standard_economy_module'}) and omit(eb,{'resources'})==omit(ea,{'resources'}) and omit(rb,{'minerals'})==omit(ra,{'minerals'}) and D(str(q.scalars(rb)['minerals']))-D(str(q.scalars(ra)['minerals']))==800,
 'same_serial_queue0_only_append_heavy_after_clear':omit(bq,{'items'})==omit(aq,{'items'}) and q.ids(q.block(bq,'items'))==[1224736779] and q.ids(q.block(aq,'items'))==[1224736779,16777257] and q.scalars(aq)=={'owner':0,'simultaneous':1,'type':'planet'} and q.scalars(q.block(aq,'location'))=={'type':2,'id':7},
 'exact_new_zone_foundry_order0_progress360_work800M':q.scalars(item)=={'queue':0,'paying_country':0,'progress':0,'progress_needed':360} and q.scalars(q.block(item,'resources'))=={'minerals':800} and q.scalars(q.block(item,'buildable_zone'))=={'zone':'zone_foundry','planet':0,'district':1,'zone_slot':2} and [(k,o) for k,v,o in q.fields(item)]==[('queue',False),('paying_country',False),('progress',False),('progress_needed',False),('resources',True),('buildable_zone',True)],
 'exact_none41_generation_reuse_all_other_items_held':[(k,v,o) for k,v,o in q.fields(bi) if k=='41']==[('41','none',False)] and not any(k=='41' for k,v,o in q.fields(ai)) and not any(k=='16777257' for k,v,o in q.fields(bi)) and omit(bi,{'41'})==omit(ai,{'16777257'}) and 16777257-41==16777216,
 'all_other_queues_and_construction_manager_fields_held':omit(bqs,{'0'})==omit(aqs,{'0'}) and omit(bcon,{'queue_mgr','item_mgr'})==omit(acon,{'queue_mgr','item_mgr'}) and omit(bqm,{'queues'})==omit(aqm,{'queues'}) and omit(bim,{'items'})==omit(aim,{'items'}),
 'all_other_top_raw_held_no_early_building_or_job_change':[(k,v,o) for k,v,o in bf if k not in {'country','construction','random_count'}]==[(k,v,o) for k,v,o in af if k not in {'country','construction','random_count'}],
 'exact_random_count_plus2_only':[(v,o) for k,v,o in bf if k=='random_count']==[('211214815',False)] and [(v,o) for k,v,o in af if k=='random_count']==[('211214817',False)],
 'normal_order_and_confirmation_native_save_actual0':all(load(st+'-execution.json')['returncode']==0 for st in ['terravore-heavy-conversion-order-click','terravore-heavy-conversion-confirm',after+'-native-save']) and all(load(st+'-execution.json')['helper_sha256']==h.sha256(run/'priority_native_ui_input_v3.py')=='801941d04cb3b4434483d22f3418187438142d66c9740367794ae75f2ac41a9f' for st in ['terravore-heavy-conversion-order-click','terravore-heavy-conversion-confirm']) and load('terravore-heavy-conversion-order-click.action.json')['client_point']==[815,244] and load('terravore-heavy-conversion-confirm.action.json')['client_point']==[629,415] and load(after+'-native-save-execution.json')['helper_sha256']==h.sha256(run/'priority_native_save.py')=='19fea261969af27e547860acead4fa010e90612d8b6d2904b1b6b11ba49ee82e',
 'current_native800M258day_quote_image_bound':h.sha256(run/'terravore-mother-heavy-current-quote-visible.jpg')==load('terravore-mother-heavy-current-quote-visible.ocr.json')['image_sha256']=='26c1a1506cc487a676d696e8f05cebf60cafcbc1ba88c41bc726b20a579295e6',
 'clear30_and_colony_ship0_exact_raw_held':q.block(bi,'1224736779')==q.block(ai,'1224736779') and q.scalars(q.block(ai,'1224736779'))['progress']==30 and q.block(bi,'16777256')==q.block(ai,'16777256') and q.scalars(q.block(ai,'16777256'))['progress']==0,
 'no_pending_strict2814_error_all_bytes_held':not[v for k,v,o in af if k=='player_event' and o and q.scalars(v).get('country')==0] and (run/(before+'-error-after.log')).read_bytes()==(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes() and h.sha256(run/(after+'-error-after.log'))=='df43a78778ff981c9add0382adb3fd127128adbc6006d6bfd7db6a194c6056eb',
}
proof={k:v for k,v in pre.items() if k not in {'status','checks','before_sha256','after_sha256','scope'}};proof.update(status='PASS_TERRAVORE_HEAVY_CONVERSION_PAYMENT_COMPONENT' if all(checks.values()) else 'FAIL',checks=checks,before_sha256=b['save_sha256'],after_sha256=a['save_sha256'],date=a['date'],actual_stockpiles=ac['effective_stockpile'],actual_heavy_order_id=16777257,actual_heavy_order_raw=item,actual_heavy_order_progress=0,calendar_ready=all(checks.values()),short_idle_war_calendar_ready=all(checks.values()),scope='One paid heavy conversion queued after clear272. Original buildings and jobs still present; no completed conversion or economic recovery claim.')
out=run/(after+'-heavy-payment-proof.json');assert not out.exists();h.write_json(out,proof);print(json.dumps({'status':proof['status'],'checks':len(checks),'failed':[k for k,v in checks.items() if v is not True]}),flush=True);assert all(checks.values()),'Original purchase retained; never repeat payment'
