"""Read-only exact native trait error reproduction, retaining production FAIL."""
import json,logging,re,shutil,sys,zipfile,hashlib
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime','--vanilla'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name)
def read(st):
 a=json.loads((run/(st+'.audit.json')).read_text('utf-8'))
 with zipfile.ZipFile(run/(st+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 return a,{k:v for k,v,o in q.fields(t) if o}
b,br=read('leader13-control-loaded');a,ar=read('leader13-control-event');pre=json.loads((run/'leader13-control-loaded-proof.json').read_text('utf-8'));obs=json.loads((run/'leader13-control-event-observation.json').read_text('utf-8'));prod=Path(json.loads(Path(m['production_pointer_backup']).read_text('utf-8'))['artifact_dir'])
pb=(prod/'terravore-defense-post-battle-repair-month-error-before.log').read_bytes();pa=(prod/'terravore-defense-post-battle-repair-month-error-after.log').read_bytes();cb=(run/'leader13-control-event-error-before.log').read_bytes();ca=(run/'leader13-control-event-error-after.log').read_bytes();pd,cd=pa[len(pb):],ca[len(cb):];normalize=lambda v:re.sub(rb'\[\d{2}:\d{2}:\d{2}\]',b'[TIME]',v)
bc={k:v for k,v,o in q.fields(br['country']) if o};ac={k:v for k,v,o in q.fields(ar['country']) if o}
target=q.block(ar['leaders'],'50331733');traits=[v.strip('"') for k,v,o in q.fields(target) if k=='traits']
checks={'actual_enabled_mods_empty':m['enabled_mods']==json.loads((user/'dlc_load.json').read_text('utf-8'))['enabled_mods']==[],'bound_load_eight_checks_PASS_execution_zero':pre['status']=='PASS_LEADER13_CONTROL_LOAD_ONLY' and len(pre['checks'])==8 and all(pre['checks'].values()) and pre['after_sha256']==b['save_sha256'] and json.loads((run/'leader13-control-load-execution.json').read_text('utf-8'))['returncode']==0,'original_SHA_pair':h.sha256(run/'leader13-control-loaded.sav')==b['save_sha256'] and h.sha256(run/'leader13-control-event.sav')==a['save_sha256'],'one_exact_native_fleet_event_receipt':obs['command']=='event leader.13 565' and obs['before_sha256']==b['save_sha256'] and obs['after_sha256']==a['save_sha256'] and json.loads((run/'leader13-control-event-execution.json').read_text('utf-8'))['returncode']==0,'same_actual_date':b['date']==a['date']=='2237.08.02','target_leader_exact_original_traits_no_gale':traits==['leader_trait_cautious','leader_trait_adaptable'],'target_ship_fleet_owner_held':q.scalars(q.block(ar['ships'],'1527'))['leader']==50331733 and q.scalars(q.block(ar['ships'],'1527'))['fleet']==565 and q.scalars(target)['country']==16777218,'all_countries_raw_held':bc==ac,'all_actual_audited_populations_held':b['pop_groups']==a['pop_groups'],'country0_actual_stocks_and_population_held':b['countries']['0']['effective_stockpile']==a['countries']['0']['effective_stockpile'] and b['colonies']['0']['actual_pop_sum']==a['colonies']['0']['actual_pop_sum'],'original_error_prefixes_preserved':pa.startswith(pb) and ca.startswith(cb),'exact144_error_increment_each':len(pd)==len(cd)==144,'entire_error_body_same_after_timestamp_normalization':normalize(pd)==normalize(cd),'exact_one_native_trait_error_no_extra':cd.count(b'councilor_trait_not_allowed')==1 and b'events/leader_events_1.txt line: 683' in cd}
sources=[Path('C:/SteamLibrary/steamapps/common/Stellaris')/s for s in ['events/leader_events_1.txt','common/on_actions/00_on_actions.txt','common/traits/00_admiral_traits.txt']]
p={'status':'PASS_SCOPED_NO_MOD_LEADER13_ERROR_REPRODUCTION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'production_error_delta_sha256':hashlib.sha256(pd).hexdigest(),'control_error_delta_sha256':hashlib.sha256(cd).hexdigest(),'error_increment_bytes':len(cd),'native_sources':[{'path':str(s),'sha256':h.sha256(s)} for s in sources],'original_production_run':str(prod),'scope':'Same 144-byte original leader.13 trait rejection reproduced with empty enabled_mods in Mod-derived world by one explicit native fleet event. Active EEP scripts unnecessary. Does not identify original natural offender, certify clean vanilla-origin generation, waive missing-definition load baseline or pass original no-new-error check.'};out=run/'leader13-control-error-reproduction-proof.json';assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original control FAIL retained'
