"""Exact native trait rejection in actual fleet scope, retaining invalid-scope FAIL."""
import json,logging,re,shutil,sys,zipfile,hashlib
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime','--vanilla'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name);readj=lambda p:json.loads(p.read_text('utf-8'))
def read(st):
 a=readj(run/(st+'.audit.json'))
 with zipfile.ZipFile(run/(st+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 return a,{k:v for k,v,o in q.fields(t) if o}
before='leader13-control-event';after='leader13-control-fleet-effect';b,br=read(before);a,ar=read(after);old=readj(run/'leader13-control-error-reproduction-proof.json');obs=readj(run/(after+'-observation.json'));pre=readj(run/(after+'-preflight.json'));prod=Path(readj(Path(m['production_pointer_backup']))['artifact_dir'])
pb=(prod/'terravore-defense-post-battle-repair-month-error-before.log').read_bytes();pa=(prod/'terravore-defense-post-battle-repair-month-error-after.log').read_bytes();cb=(run/(after+'-error-before.log')).read_bytes();ca=(run/(after+'-error-after.log')).read_bytes();pd,cd=pa[len(pb):],ca[len(cb):];norm=lambda v:re.sub(rb'\[\d{2}:\d{2}:\d{2}\]',b'[TIME]',v)
bc={k:v for k,v,o in q.fields(br['country']) if o};ac={k:v for k,v,o in q.fields(ar['country']) if o};target=q.block(ar['leaders'],'50331733');traits=[v.strip('"') for k,v,o in q.fields(target) if k=='traits']
checks={'actual_enabled_mods_empty':m['enabled_mods']==readj(user/'dlc_load.json')['enabled_mods']==[],'bound_original14_exact_three_scope_comparison_FAIL_others11_true':old['status']=='FAIL' and len(old['checks'])==14 and [k for k,v in old['checks'].items() if not v]==['exact144_error_increment_each','entire_error_body_same_after_timestamp_normalization','exact_one_native_trait_error_no_extra'] and old['after_sha256']==b['save_sha256'] and readj(run/'leader13-control-error-guard-execution.json')['returncode']==1,'original_SHA_pair':h.sha256(run/(before+'.sav'))==b['save_sha256'] and h.sha256(run/(after+'.sav'))==a['save_sha256'],'one_unique_actual_native_fleet_effect_receipt':pre['status']=='PASS_ONE_UNIQUE_NATIVE_FLEET_TARGET_ONLY' and pre['matches']==[[16777218,565,1527,50331733]] and pre['command']==obs['command'] and obs['command'].startswith('effect every_country = { every_owned_fleet = {') and obs['command'].count('fleet_event = { id = leader.13 }')==1 and obs['before_sha256']==b['save_sha256'] and obs['after_sha256']==a['save_sha256'] and readj(run/(after+'-execution.json'))['returncode']==0,'same_actual_date':b['date']==a['date']=='2237.08.02','target_leader_exact_original_traits_no_gale':traits==['leader_trait_cautious','leader_trait_adaptable'],'target_ship_fleet_owner_held':q.scalars(q.block(ar['ships'],'1527'))['leader']==50331733 and q.scalars(q.block(ar['ships'],'1527'))['fleet']==565 and q.scalars(target)['country']==16777218,'all_countries_raw_held':bc==ac,'all_actual_audited_populations_held':b['pop_groups']==a['pop_groups'],'country0_actual_stocks_and_population_held':b['countries']['0']['effective_stockpile']==a['countries']['0']['effective_stockpile'] and b['colonies']['0']['actual_pop_sum']==a['colonies']['0']['actual_pop_sum'],'original_error_prefixes_preserved':pa.startswith(pb) and ca.startswith(cb),'exact144_error_increment_each':len(pd)==len(cd)==144,'entire_error_body_same_after_timestamp_normalization':norm(pd)==norm(cd),'exact_one_native_trait_error_no_extra':cd.count(b'councilor_trait_not_allowed')==1 and b'events/leader_events_1.txt line: 683' in cd}
p={'status':'PASS_SCOPED_NO_MOD_LEADER13_ERROR_REPRODUCTION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'production_error_delta_sha256':hashlib.sha256(pd).hexdigest(),'control_error_delta_sha256':hashlib.sha256(cd).hexdigest(),'error_increment_bytes':len(cd),'native_sources':old['native_sources'],'original_production_run':str(prod),'scope':'Actual fleet-scoped native leader.13 error reproduction with empty enabled_mods. Invalid country-scope914-byte FAIL retained as separate baseline. Same exact144-byte rejection does not require active EEP scripts; no original natural offender or vanilla-origin generation identification, no production no-new-error/full-route pass.'};out=run/'leader13-control-fleet-error-reproduction-proof.json';assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original fleet-scope control FAIL retained'
