import copy,json,logging,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name);before='organic-upgrade-cancel-left-refunded';stage='organic-psicorps-building-ordered';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));eb=(user/'logs/error.log').read_bytes();(run/(stage+'-error-before.log')).write_bytes(eb)
def construction(stem):
 with zipfile.ZipFile(run/(stem+'.sav')) as z:raw=z.read('gamestate').decode('utf-8-sig')
 c=q.block(raw,'construction');queue=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');items=q.block(q.block(c,'item_mgr'),'items');ids=q.ids(q.block(queue,'items'));return ids,{str(i):q.block(items,str(i)) for i in ids},raw
bid,bi,bt=construction(before);assert bid==[];assert b['countries']['0']['effective_stockpile']['minerals']>=500
f=r.gpu_capture(stage+'-real-native-price');labels=[v['text'] for v in f['rows']];assert '\u7075\u80fd\u519b\u56e2' in labels and '480500' in labels;h.click_point(822,415,stage+'-native-replace-once');a=r.native_save(stage,b['date'],(0,));aid,ai,at=construction(stage);ac,bc=a['countries']['0'],b['countries']['0'];item=ai[str(aid[0])] if len(aid)==1 else '';s=q.scalars(item);expected_colonies=copy.deepcopy(b['colonies']);expected_colonies['0']['last_building_changed']='building_psi_corps';ea=(user/'logs/error.log').read_bytes();(run/(stage+'-error-after.log')).write_bytes(ea)
checks={'same_actual_date':a['date']==b['date']=='2305.05.02','actual500_minerals_paid':D(str(bc['effective_stockpile']['minerals']))-D(str(ac['effective_stockpile']['minerals']))==500,'all_other_actual_stocks_held':{k:v for k,v in bc['effective_stockpile'].items() if k!='minerals'}=={k:v for k,v in ac['effective_stockpile'].items() if k!='minerals'},'native_one_queue_order':bid==[] and len(aid)==1,'native_building_replaces_exact_stronghold':q.scalars(q.block(item,'buildable_planet_replace_building'))=={'building':'building_psi_corps','planet':0,'zone':0,'replace_building':50331775},'native0_of480':s.get('progress')==0 and s.get('progress_needed')==480,'native_paying_country_and_queue0':s.get('queue')==s.get('paying_country')==0,'native_cost500':q.scalars(q.block(item,'resources'))=={'minerals':500},'only_exact_operation_record_colony_difference':a['colonies']==expected_colonies,'all_raw_existing_buildings_held':q.block(bt,'buildings')==q.block(at,'buildings'),'all_raw_zones_held':q.block(bt,'zones')==q.block(at,'zones'),'no_new_errors':eb==ea}
for k in ('research_stockpile','tech_status','variables','flags','traditions','ascension_perks','government','owned_colonies'):checks[k+'_held']=bc[k]==ac[k]
for k in ('planets','pop_groups','pop_jobs','districts','deposits','situations','species'):checks[k+'_held']=a[k]==b[k]
p={'status':'PASS_NATIVE_PAID_BUILDING_ORDER' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'native_queue_ids':aid,'native_order_raw':item,'actual_minerals_after':ac['effective_stockpile']['minerals'],'scope':'One real500-mineral/480-day native PsiCorps replacement of the exact stronghold. Old buildings, all workforce and all population remain until actual completion. No full Shroud or civic acceptance.'};h.write_json(run/(stage+'-proof.json'),p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original replacement order FAIL retained; do not repay'
