import json,shutil,sys
from collections import defaultdict
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');run=Path('_runtime/heart-of-devouring/runs/20261008T103147Z');dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes();before='organic-third-latent-pre-settlement-recovery';stage='organic-third-latent-settlement';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));a=json.loads((run/(stage+'.audit.json')).read_text(encoding='utf-8'));bc,ac=b['countries']['0'],a['countries']['0'];source=a['planets']['1679'];returned=b['colonies']['38']['actual_pop_sum'];assert returned==1419
def species_counts(a,cid):
 d=defaultdict(int)
 for v in a['pop_groups'].values():
  if v['planet']==cid:d[v['key']['species']]+=v['size']
 return dict(d)
bcore=species_counts(b,0);acore=species_counts(a,0);src=species_counts(b,38);expected=dict(bcore)
for k,v in src.items():expected[k]=expected.get(k,0)+v
expected[102]=expected.get(102,0)+200
expected_vars=dict(bc['variables']);expected_vars.update(eep_c=40,eep_g=40,eep_d=12,eep_made=600,eep_entitled=600,eep_worlds=3,eep_previous_capacity=8,eep_last_capacity=4,eep_last_return=returned,eep_last_manufactured=200,eep_delta=200)
total_before=sum(b['colonies'][str(i)]['actual_pop_sum'] for i in bc['owned_colonies']);total_after=sum(a['colonies'][str(i)]['actual_pop_sum'] for i in ac['owned_colonies']);active=[v for v in a['situations'].values() if v.get('type')=='situation_eep_devouring' and v.get('killed')!='yes'];eb=(run/(stage+'-error-before.log')).read_bytes();ea=(run/(stage+'-error-after.log')).read_bytes();core=[i for i in a['planets']['7']['deposits'] if a['deposits'].get(str(i),{}).get('type')=='d_eep_core']
steps={'eep_credit_done','eep_return_done','eep_population_done','eep_crisis_done','eep_destroy_done'}
checks={'actual_endpoint_date':a['date']=='2303.09.02','same_preceding_day_baseline':b['date']=='2303.09.01','source_unowned_shattered':source.get('owner') is None and source.get('controller') is None and source['planet_class']=='pc_shattered','source_colony_removed':source.get('colony') is None and '38' not in a['colonies'],'source_steps_complete_and_active_cleared':steps<=set(source['flags']) and not {'eep_active','eep_pending'}&set(source['flags']),'no_active_EEP_task':not active,'all_settlement_variables_exact':ac['variables']==expected_vars,'C_G_40_D12_made600_worlds3':all(ac['variables'][k]==v for k,v in {'eep_c':40,'eep_g':40,'eep_d':12,'eep_made':600,'eep_worlds':3}.items()),'mother_exact_actual_return_plus200':a['colonies']['0']['actual_pop_sum']==b['colonies']['0']['actual_pop_sum']+returned+200,'country_exact_plus200':total_after==total_before+200,'mother_species_specific_conservation':acore==expected,'only_source_owned_colony_removed':ac['owned_colonies']==[i for i in bc['owned_colonies'] if i!=38],'all_other_owned_colony_actual_populations_held':all(a['colonies'][str(i)]['actual_pop_sum']==b['colonies'][str(i)]['actual_pop_sum'] for i in ac['owned_colonies'] if i!=0),'all_other_raw_pop_groups_held':{k:v for k,v in b['pop_groups'].items() if v['planet'] not in (0,38)}=={k:v for k,v in a['pop_groups'].items() if v['planet'] not in (0,38)},'latent_family_definitions_held':all(a['species'][k]==b['species'][k] for k in ('102','103')),'mother_unique_core_owned':len(core)==1 and sum('eep_core' in p['flags'] for p in a['planets'].values())==1 and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'mother_actual_capacity_value12':a['planets']['7']['variables'].get('eep_capacity_value')==12,'mother_existing_districts_held':all(a['districts'][str(i)]==b['districts'][str(i)] for i in b['colonies']['0']['districts']),'native_shroud_held':a['situations']['33554438']==b['situations']['33554438'],'no_early_final_psionic_or_stage2':ac['variables']['eep_psi']==0 and ac['variables']['eep_stage']==1,'only_EEP_notice_pending_added':set(ac['flags'])==set(bc['flags'])|{'eep_notice_pending'} and all(ac['flags'][k]==v for k,v in bc['flags'].items()),'no_new_errors':ea==eb}
for k in ('effective_stockpile','research_stockpile','tech_status','traditions','ascension_perks','government'):checks[k+'_held']=bc[k]==ac[k]
p={'status':'PASS_SCOPED' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'actual_source_return':returned,'manufactured_gain':200,'actual_country_population_before':total_before,'actual_country_population_after':total_after,'actual_mother_population_before':b['colonies']['0']['actual_pop_sum'],'actual_mother_population_after':a['colonies']['0']['actual_pop_sum'],'source_species_population_before':src,'mother_species_population_before':bcore,'mother_species_population_after':acore,'actual_EEP_variables':ac['variables'],'actual_source_after':source,'raw_economy_mirror_differences':{k:[bc['stockpile'].get(k),ac['stockpile'].get(k)] for k in set(bc['stockpile'])|set(ac['stockpile']) if bc['stockpile'].get(k)!=ac['stockpile'].get(k)},'scope':'One true native adjacent-day Q13/T32 settlement of existing latent-family planet, including capacity remainder carry and exact species-specific population conservation. Not whole civic acceptance.'};out=run/(stage+'-proof.json');assert not out.exists();out.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8');print(json.dumps({'status':p['status'],'checks':checks,'sha':a['save_sha256'],'actual_return':returned,'mother_population':p['actual_mother_population_after'],'country_population':total_after,'source_species':src}),flush=True);assert all(checks.values()),'Original third settlement failure retained'
