import hashlib,json,shutil,sys
from decimal import Decimal as D
from pathlib import Path
before,after,date,delta,*optional=sys.argv[1:];threads=D(optional[0]) if optional else None
sys.stdout.reconfigure(encoding='utf-8');r=Path('_runtime/heart-of-devouring/runs/20261008T103147Z');dest=r/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes()
b=json.loads((r/(before+'.audit.json')).read_text(encoding='utf-8'));a=json.loads((r/(after+'.audit.json')).read_text(encoding='utf-8'));bc,ac=b['countries']['0'],a['countries']['0'];state=json.loads((r/(after+'-state.json')).read_text(encoding='utf-8'))
resources=('energy','minerals','food','consumer_goods','alloys','unity');period=ac['budget_categories']['current_month'];net={k:sum((D(str(v.get(k,0))) for v in period['balance'].values()),D(0)) for k in resources};residuals={k:D(str(ac['effective_stockpile'][k]))-D(str(bc['effective_stockpile'][k]))-net[k] for k in resources}
checks={'actual_expected_date':a['date']==date,'no_new_errors':state['new_error_bytes']==0,'EEP_ledger_held':bc['variables']==ac['variables'],'EEP_flags_held':bc['flags']==ac['flags'],'AP_and_traditions_held':bc['ascension_perks']==ac['ascension_perks'] and bc['traditions']==ac['traditions'],'true_research_available':ac['research_stockpile'] is not None,'all_six_budget_residuals_zero':all(v==0 for v in residuals.values()),'owned_colony_ids_held':bc['owned_colonies']==ac['owned_colonies'],'native_founder_held':bc['native']['founder_species_ref']==ac['native']['founder_species_ref'],'mother_core_unique_and_owned':sum('eep_core' in p['flags'] for p in a['planets'].values())==1 and 'eep_core' in a['planets']['7']['flags'] and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'native_shroud_monthly_progress':D(str(a['situations']['33554438']['progress']))-D(str(b['situations']['33554438']['progress']))==D(delta)}
extra={}
if threads is not None:
 k='astral_threads';income=sum((D(str(v.get(k,0))) for v in period['income'].values()),D(0));expense=sum((D(str(v.get(k,0))) for v in period['expenses'].values()),D(0));difference=D(str(ac['effective_stockpile'][k]))-D(str(bc['effective_stockpile'][k]));extra={'astral_income':str(income),'astral_expense':str(expense),'astral_stock_change':str(difference),'astral_budget_residual':str(difference-income+expense)};checks['actual_astral_upkeep']=expense==threads;checks['astral_budget_reconciles']=difference==income-expense
p={'status':'PASS_SCOPED' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'proof_helper_sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'current_month_net':{k:str(v) for k,v in net.items()},'stock_budget_residuals':{k:str(v) for k,v in residuals.items()},'negative_primary_net_observed':[k for k,v in net.items() if v<0],**extra,'scope':'Native one-month accounting and EEP/core guards only. All actual negative balances retained; not perpetual economic closure or full civic acceptance.'}
out=r/(after+'-proof.json');assert not out.exists();out.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8');print(json.dumps(p),flush=True);assert all(checks.values()),'Original monthly accounting failure retained'
