import copy,json,logging,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.path.insert(0,'_runtime/heart-of-devouring');sys.argv=['runtime'];import runtime as r,audit_save as q
from native_selected_history import selected_history
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes()
before='organic-temple-year1-marauder-withdraw-ack';stage='organic-temple-year1-dead-volcano-ack'
def state(stem):
    a=json.loads((run/(stem+'.audit.json')).read_text(encoding='utf-8'))
    with zipfile.ZipFile(run/(stem+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
    roots=list(q.fields(t));return a,t,{k:v for k,v,o in roots if o},{q.scalars(v)['id']:v for k,v,o in roots if k=='player_event' and o and q.scalars(v).get('country')==0}
b,bt,br,bp=state(before);assert q.scalars(bp[437])['event']=='cstorms.1735' and q.scalars(q.block(bp[437],'scope'))['id']==1672
bc=b['countries']['0'];assert 'tech_volcano' not in bc['completed_technologies'] and 'tech_volcano' not in bc['research_progress_by_tech'] and 'tech_colonization_1' in bc['completed_technologies'];assert 1428 in b['planets']['1672']['deposits'] and b['deposits']['1428']['type']=='d_active_volcano'
eb=(user/'logs/error.log').read_bytes();(run/(stage+'-error-before.log')).write_bytes(eb);f=r.gpu_capture(stage+'-actual-option');rows=[v for v in f['rows'] if v['text']=='\u5f88\u8ff7\u4eba\u3002' and v['score']>=.8];assert len(rows)==1
row=rows[0];pt=tuple(round(sum(v[i] for v in row['box'])/4) for i in [0,1]);hwnd=h.focus_pid(int(h.process_record(run)['pid']));old=h.pyautogui.PAUSE
try:
    h.pyautogui.PAUSE=0;h.pyautogui.click(*h.win32gui.ClientToScreen(hwnd,pt));h.win32api.keybd_event(0,0x01,0x0008,0);h.win32api.keybd_event(0,0x01,0x0008|h.win32con.KEYEVENTF_KEYUP,0)
finally:h.pyautogui.PAUSE=old
h.write_json(run/(stage+'-choice.action.json'),{'action':'normal_native_event_choice_then_escape','native_event':437,'client_point':pt,'source_image_sha256':f['image_sha256']});r.native_save(stage,b['date'],(0,));a,at,ar,ap=state(stage);ac=a['countries']['0'];ea=(user/'logs/error.log').read_bytes();(run/(stage+'-error-after.log')).write_bytes(ea)
stocks_b,stocks_a=bc['effective_stockpile'],ac['effective_stockpile'];expected_planet=copy.deepcopy(b['planets']['1672']);expected_planet['deposits'].remove(1428);expected_planet['flags'].pop('affected_by_nexus_storm',None)
tech_b,tech_a=bc['tech_status'],ac['tech_status'];special={'stored_techpoints_for_tech','alternatives','last_increased_tech','potential','always_available_tech'}
checks={'same_actual_date':a['date']==b['date'],'no_new_errors':ea==eb,'only_pending437_removed_other_raw_held':set(ap)==set(bp)-{437} and all(bp[k]==v for k,v in ap.items()),'history_exactly_human437_option0':selected_history(at)==selected_history(bt)+[{'player_event':437,'human':1,'option':0}],'native_minerals_plus1000':D(str(stocks_a['minerals']))-D(str(stocks_b['minerals']))==D(1000),'all_other_true_stocks_held':{k:v for k,v in stocks_a.items() if k!='minerals'}=={k:v for k,v in stocks_b.items() if k!='minerals'},'affected_planet_only_deposit_and_storm_flag_removed':a['planets']['1672']==expected_planet,'all_other_planets_raw_held':{k:v for k,v in a['planets'].items() if k!='1672'}=={k:v for k,v in b['planets'].items() if k!='1672'},'all_other_deposit_definitions_held':{k:v for k,v in a['deposits'].items() if k!='1428'}=={k:v for k,v in b['deposits'].items() if k!='1428'},'removed_deposit_absent_or_same_historical_object':a['deposits'].get('1428') in [None,b['deposits']['1428']],'completed_technologies_research_banks_and_queues_held':all(bc[k]==ac[k] for k in ['completed_technologies','research_stockpile','research_queues']),'only_volcano_partial_added':set(ac['research_progress_by_tech'])==set(bc['research_progress_by_tech'])|{'tech_volcano'} and ac['research_progress_by_tech']['tech_volcano']>0 and all(ac['research_progress_by_tech'][k]==v for k,v in bc['research_progress_by_tech'].items()),'all_other_full_tech_fields_held':[(k,v,o) for k,v,o in q.fields(tech_a) if k not in special]==[(k,v,o) for k,v,o in q.fields(tech_b) if k not in special],'complete_native_country_flags_held':q.block(q.block(ar['country'],'0'),'flags')==q.block(q.block(br['country'],'0'),'flags')}
old_always=[q.unquote(v) for k,v,o in q.fields(tech_b) if k=='always_available_tech'];new_always=[q.unquote(v) for k,v,o in q.fields(tech_a) if k=='always_available_tech'];checks['always_option_only_volcano_added']=new_always.count('tech_volcano')==1 and [v for v in new_always if v!='tech_volcano']==old_always
alt_b,alt_a=q.block(tech_b,'alternatives'),q.block(tech_a,'alternatives');checks['all_other_alternatives_held']=all([q.unquote(v) for v,l,r in q.tokens(q.block(alt_a,k)) if q.unquote(v)!='tech_volcano']==[q.unquote(v) for v,l,r in q.tokens(q.block(alt_b,k))] for k in ['physics','society','engineering'])
pot_b,pot_a=dict((q.unquote(k),q.unquote(v)) for k,v,o in q.fields(q.block(tech_b,'potential'))),dict((q.unquote(k),q.unquote(v)) for k,v,o in q.fields(q.block(tech_a,'potential')));checks['all_other_potential_held']={k:v for k,v in pot_b.items() if k!='tech_volcano'}=={k:v for k,v in pot_a.items() if k!='tech_volcano'};checks['last_increased_tech_volcano']=q.scalars(tech_a).get('last_increased_tech')=='tech_volcano'
for k in ['variables','flags','traditions','ascension_perks','government','owned_colonies']:checks[('EEP_flags' if k=='flags' else k)+'_held']=bc[k]==ac[k]
for k in ['pop_groups','pop_jobs','colonies','districts','situations','species']:checks[k+'_held']=b[k]==a[k]
for k in ['construction','buildings','zones','leaders']:checks['raw_'+k+'_held']=br[k]==ar[k]
p={'status':'PASS_NATIVE_VOLCANO_SCOPE_PENDING_COST_VERIFICATION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'actual_volcano_partial':ac['research_progress_by_tech'].get('tech_volcano'),'native_research_options_before':old_always,'native_research_options_after':new_always,'tech_raw_before':tech_b,'tech_raw_after':tech_a,'affected_planet_before':b['planets']['1672'],'affected_planet_after':a['planets']['1672'],'affected_colony_before':b['colonies']['40'],'affected_colony_after':a['colonies']['40'],'scope':'Normal native dead-volcano event on physical1672, mineral reward and declared technology/deposit effects only. Full25% verification requires actual same-date F4 cost; not EEP reward or script grant.'};h.write_json(run/(stage+'-proof.json'),p);print(json.dumps({'status':p['status'],'checks':checks,'actual_partial':p['actual_volcano_partial'],'sha':a['save_sha256']}),flush=True);assert all(checks.values()),'Original native event failure retained; no replay'
