import json,logging,math,shutil,sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime']
import runtime as r
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name)
before='organic-psicorps-completed-nextmonth';stage='organic-fourth-Q22-latent-devour-begin';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));eb=(user/'logs/error.log').read_bytes();source_before=b['planets']['711'];population=b['colonies']['29']['actual_pop_sum'];assert source_before['owner']==source_before['controller']==0 and source_before['planet_size']==22;assert all(b['pop_groups'][str(i)]['key']['species'] in (102,103) for i in b['colonies']['29']['pop_groups'])
f=r.gpu_capture(stage+'-actual-decision');label='\u541e\u566c\uff1a\u732e\u4e8e\u552f\u4e00\u738b\u5ea7';rows=[v for v in f['rows'] if v['text']==label and 110<v['box'][0][1]<155];assert len(rows)==1;row=rows[0];point=(round(sum(p[0] for p in row['box'])/4),round(sum(p[1] for p in row['box'])/4));h.click_point(*point,stage+'-actual-native-decision-click')
f=r.gpu_capture(stage+'-after-native-click');print(json.dumps({'image':str(f['image']),'rows':[v['text'] for v in f['rows']]}),flush=True)
a=r.native_save(stage,b['date'],(0,));bc,ac=b['countries']['0'],a['countries']['0'];source=a['planets']['711'];active=[(k,v) for k,v in a['situations'].items() if v.get('type')=='situation_eep_devouring' and v.get('killed')!='yes'];ea=(user/'logs/error.log').read_bytes();(run/(stage+'-error-after.log')).write_bytes(ea)
checks={'same_actual_date':a['date']==b['date'],'no_new_errors':ea==eb,'Q22_T53_frozen':source['variables'].get('eep_q')==22 and source['variables'].get('eep_months')==math.ceil(22*2.4),'all_actual_existing_latent_family_recognized':source['variables'].get('eep_seed_existing')==population,'source_still_owned_active':source.get('owner')==source.get('controller')==0 and 'eep_active' in source['flags'],'one_native_EEP_situation_progress_zero':len(active)==1 and active[0][1]['progress']==0 and active[0][1]['target']['id']==711,'original_shroud_held':a['situations']['33554438']==b['situations']['33554438']}
for k in ('effective_stockpile','research_stockpile','tech_status','variables','flags','traditions','ascension_perks','government','native'):checks[k+'_held']=bc[k]==ac[k]
for k in ('pop_groups','pop_jobs','colonies','districts','deposits','species'):checks[k+'_held']=a[k]==b[k]
checks['all_other_planets_held']={k:v for k,v in a['planets'].items() if k!='711'}=={k:v for k,v in b['planets'].items() if k!='711'}
mirror={k:[bc['stockpile'].get(k),ac['stockpile'].get(k)] for k in set(bc['stockpile'])|set(ac['stockpile']) if bc['stockpile'].get(k)!=ac['stockpile'].get(k)}
p={'status':'PASS_SCOPED' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'source_before':source_before,'source_after':source,'active_situations':active,'raw_economy_mirror_differences':mirror,'scope':'Existing owned latent-psionic family Q22 source, actual native decision with no seeding or early reward. Freeze T53; future natural growth and settlement still pending.'}
h.write_json(run/(stage+'-proof.json'),p);print(json.dumps({'checks':checks,'sha':a['save_sha256'],'source_variables':source['variables'],'situations':active,'mirror':mirror}),flush=True);assert all(checks.values()),'Original fourth-source native begin failure retained'
