import json,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
before,after,date,phase,months,source_progress=sys.argv[1:];months=int(months);source_progress=int(source_progress)
assert phase in ['mine_done','mine_month','temple_done','temple_month']
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');import audit_save as q
run=Path('_runtime/heart-of-devouring/runs/20261008T103147Z');dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes()
def state(stem):return json.loads((run/(stem+'.audit.json')).read_text(encoding='utf-8'))
def raw(stem):
    with zipfile.ZipFile(run/(stem+'.sav')) as z:return z.read('gamestate').decode('utf-8-sig')
def queue(t):
    c=q.block(t,'construction');sq=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');it=q.block(q.block(c,'item_mgr'),'items');ids=q.ids(q.block(sq,'items'))
    return ids,{str(i):q.block(it,str(i)) for i in ids}
b,a=state(before),state(after);initial=state('organic-fourth-Q22-latent-devour-begin');bt,at=raw(before),raw(after);bid,bi=queue(bt);aid,ai=queue(at);bc,ac=b['countries']['0'],a['countries']['0'];bb=q.block(bt,'buildings');ab=q.block(at,'buildings');bz=q.block(bt,'zones');az=q.block(at,'zones');archive=q.ids(q.block(q.block(az,'1'),'buildings'));temple_done=phase in ['temple_done','temple_month'];new_temples=[i for i in archive if i not in [2,237]]
pending=[q.scalars(v) for k,v,o in q.fields(at) if k=='player_event' and o and q.scalars(v).get('country')==0];source=a['planets']['711'];active=[(k,v) for k,v in a['situations'].items() if v.get('type')=='situation_eep_devouring' and v.get('killed')!='yes'];telepaths=[v for v in a['pop_jobs'].values() if v['planet']==0 and v['type']=='telepath']
checks={'actual_date':a['date']==date,'no_new_errors':(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes(),'no_pending_native_events':not pending,'all_EEP_variables_held':bc['variables']==ac['variables'],'all_country_flags_held':bc['flags']==ac['flags'],'AP_traditions_government_owned_colonies_held':all(bc[k]==ac[k] for k in ['ascension_perks','traditions','government','owned_colonies']),'latent_family_definitions_held':all(b['species'][k]==a['species'][k] for k in ['102','103']),'mother_unique_core_owned':sum('eep_core' in v['flags'] for v in a['planets'].values())==1 and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'earned_capacity12_held':a['planets']['7']['variables']['eep_capacity_value']==12,'native_same_stage2_shroud_exact_delta':a['situations']['33554438']['stage']==b['situations']['33554438']['stage']==1 and D(str(a['situations']['33554438']['progress']))-D(str(b['situations']['33554438']['progress']))==D('3.75')*months,'native_threads_exact':D(str(ac['effective_stockpile']['astral_threads']))-D(str(bc['effective_stockpile']['astral_threads']))==3*months,'source_Q22_T53_seed_frozen':source['variables']['eep_q']==22 and source['variables']['eep_months']==53 and source['variables']['eep_seed_existing']==initial['planets']['711']['variables']['eep_seed_existing'],'source_owned_active_and_alive':source['owner']==source['controller']==0 and 'eep_active' in source['flags'] and a['colonies']['29']['actual_pop_sum']>0,'exact_source_situation_progress':len(active)==1 and active[0][0]=='50331651' and active[0][1]['target']['id']==711 and active[0][1]['progress']==source_progress,'six_default_zone_buildings_and_zone_held':q.block(az,'0')==q.block(bz,'0') and all(q.block(ab,str(i))==q.block(bb,str(i))!='' for i in [0,280,3,16777262,50331657,248]),'native_corps_type_held':q.scalars(q.block(ab,'280'))=={'type':'building_psi_corps','position':1},'native_telepath200_active':len(telepaths)==1 and telepaths[0]['workforce']==telepaths[0]['max_workforce']==200,'two_old_temples_raw_held':all(q.block(ab,str(i))==q.block(bb,str(i))!='' for i in [2,237]),'mine5_and_farm6_exact':a['districts']['2']['level']==5 and a['districts']['3']['level']==6,'native_miner1000_farmer1800':a['pop_jobs']['26']['workforce']==a['pop_jobs']['26']['max_workforce']==1000 and a['pop_jobs']['27']['workforce']==a['pop_jobs']['27']['max_workforce']==1800,'native_priest_bureaucrat_capacity':a['pop_jobs']['19']['max_workforce']==(1240 if temple_done else 1040),'native_priest_bureaucrat_full':a['pop_jobs']['19']['workforce']==a['pop_jobs']['19']['max_workforce'],'all_primary_actual_stocks_positive':all(ac['effective_stockpile'][k]>0 for k in ['energy','minerals','food','consumer_goods','alloys','unity']),'housing_amenities_positive':a['colonies']['0']['free_housing']>0 and a['colonies']['0']['free_amenities']>0}
if phase=='mine_done':checks.update(native_only_mine_order_removed=bid==[167772187,218103840] and aid==[218103840],native_temple_raw0_held=ai.get('218103840')==bi['218103840'],archive_zone_held=q.block(az,'1')==q.block(bz,'1'))
elif phase=='mine_month':checks.update(native_only_temple_order=bid==aid==[218103840],native_temple_only_progress30=ai.get('218103840')==bi['218103840'].replace('progress=0\n','progress=30\n',1),archive_zone_held=q.block(az,'1')==q.block(bz,'1'))
elif phase=='temple_done':checks.update(native_temple_order_removed=bid==[218103840] and aid==[],native_only_one_temple_added_to_archive=len(new_temples)==1 and set(archive)=={2,237,new_temples[0]},native_third_temple_position2=len(new_temples)==1 and q.scalars(q.block(ab,str(new_temples[0])))=={'type':'building_temple','position':2})
else:checks.update(native_queue_empty_held=bid==aid==[],archive_zone_and_all_three_buildings_raw_held=q.block(az,'1')==q.block(bz,'1') and all(q.block(ab,str(i))==q.block(bb,str(i)) for i in archive))
balance=ac['budget_categories']['current_month']['balance'];net={k:str(sum((D(str(v.get(k,0))) for v in balance.values()),D(0))) for k in ['energy','minerals','food','consumer_goods','alloys','unity']}
p={'status':'PASS_PAID_NATIVE_CHAIN_PHASE' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'phase':phase,'native_pending':pending,'native_queue_before':bid,'native_queue_after':aid,'archive_building_ids':archive,'new_temple_ids':new_temples,'actual_primary_net':net,'actual_stocks':ac['effective_stockpile'],'source_actual_pop':a['colonies']['29']['actual_pop_sum'],'mother_actual_pop':a['colonies']['0']['actual_pop_sum'],'native_source_situation':active,'scope':'One real paid construction or monthly phase with concurrent natural Q22 source. Primary negative balances are recorded; not whole civic acceptance.'}
out=run/(after+'-chain-proof.json');assert not out.exists();out.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8');print(json.dumps(p),flush=True);assert all(checks.values()),'Original native chain FAIL retained; stop next date advance'
