import json,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
before,after,date,progress,weather_days,source_progress,shroud_delta=sys.argv[1:];done=progress=='done';weather_days=int(weather_days);source_progress=int(source_progress)
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');import audit_save as q
run=Path('_runtime/heart-of-devouring/runs/20261008T103147Z');dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes()
def state(stem):return json.loads((run/(stem+'.audit.json')).read_text(encoding='utf-8'))
def raw(stem):
    with zipfile.ZipFile(run/(stem+'.sav')) as z:return z.read('gamestate').decode('utf-8-sig')
def queue(t):
    c=q.block(t,'construction');sq=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');it=q.block(q.block(c,'item_mgr'),'items');ids=q.ids(q.block(sq,'items'))
    return ids,{str(i):q.block(it,str(i)) for i in ids}
def anonymous(text):
    rows=[];depth=0;start=None
    for token,l,r in q.tokens(text):
        if token=='{':
            if depth==0:start=r
            depth+=1
        elif token=='}':
            assert depth>0;depth-=1
            if depth==0:rows.append(q.scalars(text[start:l]))
        elif depth==0:raise ValueError('Expected anonymous modifier object')
    assert depth==0;return rows
b,a=state(before),state(after);bt,at=raw(before),raw(after);bid,bi=queue(bt);aid,ai=queue(at);bc,ac=b['countries']['0'],a['countries']['0'];bb=q.block(bt,'buildings');ab=q.block(at,'buildings');bz=q.block(bt,'zones');az=q.block(at,'zones');source=a['planets']['711'];active=[(k,v) for k,v in a['situations'].items() if v.get('type')=='situation_eep_devouring' and v.get('killed')!='yes'];telepaths=[v for v in a['pop_jobs'].values() if v['planet']==0 and v['type']=='telepath'];weather=[v for v in anonymous(q.block(a['planets']['7']['modifiers'],'items')) if v.get('modifier')=='electric_storm_aftermath_modifier_severity_3'];pending=[q.scalars(v) for k,v,o in q.fields(at) if k=='player_event' and o and q.scalars(v).get('country')==0]
period=ac['budget_categories']['current_month'];thread_income={k:v['astral_threads'] for k,v in period['income'].items() if v.get('astral_threads')};thread_expense=sum((D(str(v.get('astral_threads',0))) for v in period['expenses'].values()),D(0));balance=period['balance'];net={k:str(sum((D(str(v.get(k,0))) for v in balance.values()),D(0))) for k in ['energy','minerals','food','consumer_goods','alloys','unity']}
checks={'actual_date':a['date']==date,'no_new_errors':(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes(),'no_pending_native_events':not pending,'all_EEP_variables_held':bc['variables']==ac['variables'],'all_country_flags_held':bc['flags']==ac['flags'],'AP_traditions_government_owned_colonies_held':all(bc[k]==ac[k] for k in ['ascension_perks','traditions','government','owned_colonies']),'latent_family_definitions_held':all(b['species'][k]==a['species'][k] for k in ['102','103']),'mother_unique_core_owned':sum('eep_core' in v['flags'] for v in a['planets'].values())==1 and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'earned_capacity12_held':a['planets']['7']['variables']['eep_capacity_value']==12,'native_same_stage2_shroud_exact_delta':a['situations']['33554438']['stage']==b['situations']['33554438']['stage']==1 and D(str(a['situations']['33554438']['progress']))-D(str(b['situations']['33554438']['progress']))==D(shroud_delta),'native_weather_remaining_days_exact':len(weather)==1 and weather[0]['days']==weather_days,'native_thread_upkeep0_and_real_stock_positive':thread_expense==0 and ac['effective_stockpile']['astral_threads']>0,'source_Q22_T53_seed2516_frozen':source['variables']['eep_q']==22 and source['variables']['eep_months']==53 and source['variables']['eep_seed_existing']==2516,'source_owned_active_and_alive':source['owner']==source['controller']==0 and 'eep_active' in source['flags'] and a['colonies']['29']['actual_pop_sum']>0,'exact_source_situation_progress':len(active)==1 and active[0][0]=='50331651' and active[0][1]['target']['id']==711 and active[0][1]['progress']==source_progress,'raw_default_zone_and_archive_held':q.block(az,'0')==q.block(bz,'0') and q.block(az,'1')==q.block(bz,'1'),'all_eight_mother_buildings_raw_held':all(q.block(ab,str(i))==q.block(bb,str(i))!='' for i in [0,280,3,16777262,50331657,248,2,237]),'native_telepath200_active':len(telepaths)==1 and telepaths[0]['workforce']==telepaths[0]['max_workforce']==200,'native_mine_expected_and_farm6':a['districts']['2']['level']==(5 if done else 4) and a['districts']['3']['level']==6,'native_miner_expected_farmer1800':a['pop_jobs']['26']['workforce']==a['pop_jobs']['26']['max_workforce']==(1000 if done else 800) and a['pop_jobs']['27']['workforce']==a['pop_jobs']['27']['max_workforce']==1800,'native_priest_bureaucrat1040':a['pop_jobs']['19']['max_workforce']==a['pop_jobs']['19']['workforce']==1040,'all_primary_actual_stocks_positive':all(ac['effective_stockpile'][k]>0 for k in ['energy','minerals','food','consumer_goods','alloys','unity']),'housing_amenities_positive':a['colonies']['0']['free_housing']>0 and a['colonies']['0']['free_amenities']>0,'native_temple_order_raw0_held':ai.get('218103840')==bi.get('218103840') and q.scalars(ai.get('218103840','')).get('progress')==0}
if done:checks['native_only_mine_order_removed']=bid==[167772187,218103840] and aid==[218103840]
else:
    old=q.scalars(bi['167772187'])['progress'];expected=bi['167772187'].replace('progress='+str(old)+'\n','progress='+str(progress)+'\n',1)
    checks.update(native_queue_ids_held=bid==aid==[167772187,218103840],native_only_exact_mine_progress_changed=ai.get('167772187')==expected)
p={'status':'PASS_NATIVE_STORM_CHECKPOINT' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'native_pending':pending,'native_queue_before':bid,'native_queue_after':aid,'native_mine_raw':ai.get('167772187'),'native_storm_modifier':weather,'native_astral_income_by_category':thread_income,'native_astral_expense':str(thread_expense),'actual_thread_stock_before':bc['effective_stockpile']['astral_threads'],'actual_thread_stock_after':ac['effective_stockpile']['astral_threads'],'actual_primary_net':net,'actual_primary_stocks':ac['effective_stockpile'],'mother_actual_pop':a['colonies']['0']['actual_pop_sum'],'source_actual_pop':a['colonies']['29']['actual_pop_sum'],'scope':'Real0.35-speed native weather construction checkpoint, existing paid queue and concurrent Q22 source. No weather removal, completion/resource grant or whole route acceptance.'}
out=run/(after+'-storm-proof.json');assert not out.exists();out.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8');print(json.dumps(p),flush=True);assert all(checks.values()),'Original storm checkpoint failure retained; stop further date advance'
