import json,logging,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
start,stage,kind=sys.argv[1:];assert kind in ('farming','mining');sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime']
import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes();b=json.loads((run/(start+'.audit.json')).read_text(encoding='utf-8'));eb=(user/'logs/error.log').read_bytes();district='district_'+kind;cn='\u5efa\u9020'+('\u519c\u4e1a' if kind=='farming' else '\u91c7\u77ff')+'\u533a\u5212';point=(674,439) if kind=='farming' else (464,439)
f=r.gpu_capture(stage+'-real-native-price');assert cn in [v['text'] for v in f['rows']] and '240300' in [v['text'] for v in f['rows']];h.click_point(*point,stage+'-real-native-order');a=r.native_save(stage,b['date'],(0,));ea=(user/'logs/error.log').read_bytes();(run/(stage+'-error-after.log')).write_bytes(ea);bc,ac=b['countries']['0'],a['countries']['0']
def queue(name):
 with zipfile.ZipFile(run/(name+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 c=q.block(t,'construction');sq=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');items=q.block(q.block(c,'item_mgr'),'items');return q.ids(q.block(sq,'items')),{k:v for k,v,o in q.fields(items) if o}
bid,bi=queue(start);aid,ai=queue(stage);item=ai.get(str(aid[-1]),'') if aid else '';sc=q.scalars(item);changes={i:{k:[b['colonies'].get(i,{}).get(k),v] for k,v in c.items() if b['colonies'].get(i,{}).get(k)!=v} for i,c in a['colonies'].items() if c!=b['colonies'].get(i)};old_changed=b['colonies']['0']['last_district_changed'];expected_changes={} if old_changed==district else {'0':{'last_district_changed':[old_changed,district]}}
checks={'same_actual_date':a['date']==b['date']=='2305.05.02','actual_300_minerals_paid':D(str(bc['effective_stockpile']['minerals']))-D(str(ac['effective_stockpile']['minerals']))==300,'all_other_effective_stock_held':{k:v for k,v in bc['effective_stockpile'].items() if k!='minerals'}=={k:v for k,v in ac['effective_stockpile'].items() if k!='minerals'},'actual_research_banks_held':bc['research_stockpile']==ac['research_stockpile'],'full_tech_status_held':bc['tech_status']==ac['tech_status'],'only_one_new_queue_item':len(aid)==len(bid)+1 and aid[:-1]==bid and all(ai[str(i)]==bi[str(i)] for i in bid),'mother_country_exact_district':sc.get('queue')==sc.get('paying_country')==0 and q.scalars(q.block(item,'buildable_district'))=={'district':district,'planet':0},'native_cost300':q.scalars(q.block(item,'resources'))=={'minerals':300},'native_progress0_needed240':sc.get('progress')==0 and sc.get('progress_needed')==240,'only_precise_operation_record_colony_change':changes==expected_changes,'no_new_errors':ea==eb}
for k in ('variables','flags','traditions','ascension_perks','government'):checks[k+'_held']=bc[k]==ac[k]
for k in ('pop_groups','pop_jobs','planets','districts','deposits','situations','species'):checks[k+'_held']=a[k]==b[k]
p={'status':'PASS_SCOPED' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'native_queue_before':bid,'native_queue_after':aid,'new_native_order_raw':item,'all_raw_colony_differences':changes,'raw_economy_mirror_differences':{k:[bc['stockpile'].get(k),ac['stockpile'].get(k)] for k in set(bc['stockpile'])|set(ac['stockpile']) if bc['stockpile'].get(k)!=ac['stockpile'].get(k)},'scope':'Normal paid native district construction in C40/D12 capacity earned from actual latent-family devour; no early completion or resource/workforce grant.'};h.write_json(run/(stage+'-proof.json'),p);print(json.dumps({'status':p['status'],'checks':checks,'sha':a['save_sha256'],'queue_ids':aid,'colony_diff':changes}),flush=True);assert all(checks.values()),'Original paid native order failure retained; do not repeat payment'
