import json,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
before,after,date,progress,threads=sys.argv[1:];progress=int(progress);threads=D(threads)
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');import audit_save as q
run=Path('_runtime/heart-of-devouring/runs/20261008T103147Z');dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes()
b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));a=json.loads((run/(after+'.audit.json')).read_text(encoding='utf-8'))
def raw(stem):
    with zipfile.ZipFile(run/(stem+'.sav')) as z:return z.read('gamestate').decode('utf-8-sig')
def queue(t):
    c=q.block(t,'construction');sq=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');items=q.block(q.block(c,'item_mgr'),'items');ids=q.ids(q.block(sq,'items'))
    return ids,{str(i):q.block(items,str(i)) for i in ids}
bt,at=raw(before),raw(after);bid,bi=queue(bt);aid,ai=queue(at);bc,ac=b['countries']['0'],a['countries']['0']
pending=[q.scalars(v) for k,v,o in q.fields(at) if k=='player_event' and o and q.scalars(v).get('country')==0]
old_progress=q.scalars(bi['167772186'])['progress'];expected=bi['167772186'].replace('progress='+str(old_progress)+'\n','progress='+str(progress)+'\n',1)
bs=q.block(q.block(q.block(bt,'situations'),'situations'),'33554438');ass=q.block(q.block(q.block(at,'situations'),'situations'),'33554438')
checks={'actual_expected_date':a['date']==date,'no_new_errors':(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes(),'no_pending_native_events':not pending,'native_queue_ids_held':aid==bid==[167772186,167772187,218103840],'native_first_only_exact_progress_changed':ai.get('167772186')==expected,'native_later_two_orders_raw_held':all(ai.get(str(i))==bi[str(i)] for i in [167772187,218103840]),'native_no_active_corps_stage2_progress502':a['situations']['33554438']['stage']==1 and a['situations']['33554438']['progress']==502 and a['situations']['33554438']['last_month_progress']==0,'native_situation_raw_held':ass==bs,'no_mother_telepath_job_created':not any(v['planet']==0 and v['type'] in ['telepath','dystopian_telepath','telepath_drone'] for v in a['pop_jobs'].values()),'raw_eight_existing_mother_buildings_held':all(q.block(q.block(at,'buildings'),str(i))==q.block(q.block(bt,'buildings'),str(i))!='' for i in [0,50331775,3,16777262,50331657,248,2,237]),'mother_soldiers200_held':a['pop_jobs']['33555163']['workforce']==a['pop_jobs']['33555163']['max_workforce']==200,'native_threads_exact':D(str(ac['effective_stockpile']['astral_threads']))==threads,'EEP_variables_held':bc['variables']==ac['variables'],'EEP_flags_held':bc['flags']==ac['flags'],'AP_traditions_government_owned_colonies_held':all(bc[k]==ac[k] for k in ['ascension_perks','traditions','government','owned_colonies']),'latent_family_definitions_held':all(b['species'][k]==a['species'][k] for k in ['102','103']),'mother_unique_core_owned':sum('eep_core' in v['flags'] for v in a['planets'].values())==1 and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'earned_capacity12_held':a['planets']['7']['variables']['eep_capacity_value']==12,'mine4_and_farm6_held':a['districts']['2']['level']==4 and a['districts']['3']['level']==6,'miner800_farmer1800_held':a['pop_jobs']['26']['max_workforce']==800 and a['pop_jobs']['27']['max_workforce']==1800,'all_primary_actual_stocks_positive':all(ac['effective_stockpile'][k]>0 for k in ['energy','minerals','food','consumer_goods','alloys','unity'])}
p={'status':'PASS_NATIVE_INCOMPLETE_CORPS_GUARDS' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'native_pending':pending,'native_queue_after':aid,'native_first_order_raw':ai.get('167772186'),'actual_primary_stocks':ac['effective_stockpile'],'actual_mother_pop':a['colonies']['0']['actual_pop_sum'],'scope':'Read-only native unfinished480-day Corps guards. No early telepath job, budget/grant or full civic acceptance.'}
out=run/(after+'-construction-proof.json');assert not out.exists();out.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8');print(json.dumps(p),flush=True);assert all(checks.values()),'Original checkpoint FAIL retained; stop further native calendar'
