import hashlib,json,shutil,sys
from decimal import Decimal as D,ROUND_DOWN
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');import audit_save as q
run=Path('_runtime/heart-of-devouring/runs/20261008T103147Z');dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes();before='organic-third-latent-pre-settlement-recovery';after='organic-third-latent-settlement';original=run/(after+'-proof.json');original_bytes=original.read_bytes();old=json.loads(original_bytes);b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));a=json.loads((run/(after+'.audit.json')).read_text(encoding='utf-8'));bc,ac=b['countries']['0'],a['countries']['0'];research=('physics_research','society_research','engineering_research');speed=D('1.13');unit=D('.00001')
checks={k:v for k,v in old['checks'].items() if k not in ('source_colony_removed','all_other_raw_pop_groups_held','effective_stockpile_held','research_stockpile_held','tech_status_held')}
checks['source_logically_destroyed_empty_historical_object']=a['planets']['1679']['planet_class']=='pc_shattered' and a['planets']['1679'].get('owner') is None and 38 not in ac['owned_colonies'] and a['colonies']['38']['actual_pop_sum']==0 and not a['colonies']['38']['pop_groups']
checks['all_nonresearch_effective_stock_held']={k:v for k,v in bc['effective_stockpile'].items() if k not in research}=={k:v for k,v in ac['effective_stockpile'].items() if k not in research}
def bank_account(bc,ac):
 net={k:sum((D(str(v.get(k,0))) for v in ac['budget_categories']['current_month']['balance'].values()),D(0)) for k in research};delta={k:D(str(ac['research_stockpile'][k]))-D(str(bc['research_stockpile'][k])) for k in research};expected={k:(net[k]*speed).quantize(unit,rounding=ROUND_DOWN) for k in research};return {'net_research':{k:str(v) for k,v in net.items()},'actual_stored_bank_delta':{k:str(v) for k,v in delta.items()},'expected_native_speed_truncated_credit':{k:str(v) for k,v in expected.items()},'exact_all_three':delta==expected}
actual=bank_account(bc,ac);checks['all_three_actual_research_banks_exact_native_month_credit']=actual['exact_all_three'];tech_b,tech_a=[{k:(v,o) for k,v,o in q.fields(c['tech_status'])} for c in (bc,ac)];checks['complete_other_tech_status_fields_held']={k:v for k,v in tech_b.items() if k!='stored_techpoints'}=={k:v for k,v in tech_a.items() if k!='stored_techpoints'}
controls=[]
for x,y in (('organic-shroud-thread87-corrected','organic-third-latent-devour-month23'),('organic-foundry-workforce-limited','organic-foundry-limit-nextmonth')):
 cb=json.loads((run/(x+'.audit.json')).read_text(encoding='utf-8'));ca=json.loads((run/(y+'.audit.json')).read_text(encoding='utf-8'));p=bank_account(cb['countries']['0'],ca['countries']['0']);p.update(before_sha256=cb['save_sha256'],after_sha256=ca['save_sha256'],EEP_variables_held=cb['countries']['0']['variables']==ca['countries']['0']['variables']);controls.append(p)
checks['two_existing_no_settlement_month_controls_match_native_bank_account']=all(p['exact_all_three'] and p['EEP_variables_held'] for p in controls)
cached={'happiness','crime','power','housing_usage','amenities_usage','approval_modifier'};bg={k:v for k,v in b['pop_groups'].items() if v['planet'] not in (0,38)};ag={k:v for k,v in a['pop_groups'].items() if v['planet'] not in (0,38)};checks['all_other_raw_group_ids_held']=set(bg)==set(ag);changes={k:{f:[bg[k].get(f),ag[k].get(f)] for f in set(bg[k])|set(ag[k]) if bg[k].get(f)!=ag[k].get(f)} for k in bg if bg[k]!=ag.get(k)};checks['other_groups_only_observed_native_derived_fields_change']=all(set(v)<=cached for v in changes.values());checks['other_group_planet_size_species_category_all_held']=all(all(bg[k].get(f)==ag[k].get(f) for f in ('planet','size','key')) for k in bg);checks['original_full_FAIL_bytes_unchanged']=original.read_bytes()==original_bytes
image=run/'organic-third-native-research-speed-ui.jpg';ocr=run/'organic-third-native-research-speed-ui.ocr.json';checks['real_native_UI_evidence_bound']=image.exists() and ocr.exists() and json.loads(ocr.read_text(encoding='utf-8'))['image_sha256']==hashlib.sha256(image.read_bytes()).hexdigest()
p={'status':'PASS_SCOPED' if all(checks.values()) else 'FAIL','checks':checks,'original_full_FAIL_sha256':hashlib.sha256(original_bytes).hexdigest(),'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'actual_research_bank_account':actual,'existing_no_settlement_controls':controls,'other_group_raw_derived_differences':changes,'native_research_UI':{'image':image.name,'image_sha256':hashlib.sha256(image.read_bytes()).hexdigest(),'observation':'Physics, society and engineering each show +13% in actual F4 UI; all three visually inspected. OCR explicitly captures the physics +13% row.'},'scope':'Independent limited settlement supplement: logical native colony destruction, exact existing-group population conservation, unchanged nonresearch stocks, and actual native research-speed bank credit corroborated by two no-settlement month originals. Original full FAIL remains FAIL; not full raw identity or whole civic acceptance.'};out=run/'organic-third-latent-settlement-independent-supplement.json';assert not out.exists();out.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8');print(json.dumps({'status':p['status'],'checks':checks,'actual_bank_account':actual,'raw_cache_changed_group_count':len(changes)}));assert all(checks.values())
