import json,logging,shutil,sys,zipfile
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name)
before='organic-unintended-native-upgrade';stage='organic-unintended-upgrade-cancelled';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));baseline=json.loads((run/'organic-native-market-buy1000.audit.json').read_text(encoding='utf-8'));eb=(user/'logs/error.log').read_bytes();(run/(stage+'-error-before.log')).write_bytes(eb)
with zipfile.ZipFile(run/(before+'.sav')) as z:raw=z.read('gamestate').decode('utf-8-sig')
c=q.block(raw,'construction');queue=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');item=q.block(q.block(q.block(c,'item_mgr'),'items'),'150994970');assert q.ids(q.block(queue,'items'))==[150994970] and q.scalars(item)['progress']==0 and q.scalars(q.block(item,'resources'))=={'minerals':800}
hwnd=h.focus_pid(h.process_record(run)['pid']);desk=h.win32gui.ClientToScreen(hwnd,(790,310));h.pyautogui.click(*desk,button='right');h.write_json(run/(stage+'-native-cancel.action.json'),{'action':'native_right_click_exact_unintended_queue_entry','client_point':[790,310],'queue_item':150994970});h.pyautogui.moveTo(*r.desktop_point(20,740),duration=.2);f=r.gpu_capture(stage+'-actual-native-result');print(json.dumps({'image':f['image'],'labels':[v['text'] for v in f['rows']]}),flush=True)
a=r.native_save(stage,b['date'],(0,));ac,bc=a['countries']['0'],b['countries']['0'];ea=(user/'logs/error.log').read_bytes();(run/(stage+'-error-after.log')).write_bytes(ea)
with zipfile.ZipFile(run/(stage+'.sav')) as z:raw=z.read('gamestate').decode('utf-8-sig')
c=q.block(raw,'construction');queue=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');checks={'same_actual_date':a['date']==b['date']=='2305.05.02','native_queue_empty':q.ids(q.block(queue,'items'))==[],'actual800_minerals_refunded':D(str(ac['effective_stockpile']['minerals']))-D(str(bc['effective_stockpile']['minerals']))==800,'exact_full_actual_stocks_restored':ac['effective_stockpile']==baseline['countries']['0']['effective_stockpile'],'no_new_errors':ea==eb}
for k in ('research_stockpile','tech_status','variables','flags','traditions','ascension_perks','government','owned_colonies'):checks[k+'_held']=ac[k]==bc[k]
for k in ('colonies','pop_groups','pop_jobs','planets','districts','deposits','situations','species'):checks[k+'_held']=a[k]==b[k]
p={'status':'PASS_NATIVE_CANCELLATION_SCOPE' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'original_pre_misclick_sha256':baseline['save_sha256'],'actual_minerals_after':ac['effective_stockpile']['minerals'],'scope':'Normal native cancellation/refund of a zero-progress unintended major-capital upgrade. Last operation record retained; no save editing or calendar rollback.'};h.write_json(run/(stage+'-proof.json'),p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original native cancellation guard failure retained; no second cancel'
