import json,logging,shutil,sys
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name)
before='organic-psicorps-tradition-confirmed';stage='organic-native-market-buy1000';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));eb=(user/'logs/error.log').read_bytes();(run/(stage+'-error-before.log')).write_bytes(eb)
f=r.gpu_capture(stage+'-actual-native-price');labels=[v['text'] for v in f['rows']];assert '+1000' in labels and '-1417' in labels and '\u56fd\u5185\u8d38\u6613\u5e02\u573a' in labels and '22809' in labels
h.click_point(191,332,stage+'-real-paid-trade-once');h.pyautogui.moveTo(*r.desktop_point(20,740),duration=.2);fafter=r.gpu_capture(stage+'-real-native-result');a=r.native_save(stage,b['date'],(0,));bc,ac=b['countries']['0'],a['countries']['0'];paid=D(str(bc['effective_stockpile']['trade']))-D(str(ac['effective_stockpile']['trade']));ea=(user/'logs/error.log').read_bytes();(run/(stage+'-error-after.log')).write_bytes(ea)
checks={'same_actual_date':a['date']==b['date']=='2305.05.02','actual_minerals_exact1000':D(str(ac['effective_stockpile']['minerals']))-D(str(bc['effective_stockpile']['minerals']))==1000,'actual_trade_cost_positive_affordable':0<paid<=D(str(bc['effective_stockpile']['trade'])),'actual_native_price_matches_display_precision':abs(paid-D('1417'))<1,'all_other_actual_stocks_including_energy_held':{k:v for k,v in bc['effective_stockpile'].items() if k not in ('trade','minerals')}=={k:v for k,v in ac['effective_stockpile'].items() if k not in ('trade','minerals')},'no_new_errors':ea==eb}
for k in ('research_stockpile','tech_status','variables','flags','ascension_perks','traditions','government','owned_colonies'):checks[k+'_held']=bc[k]==ac[k]
for k in ('pop_groups','pop_jobs','colonies','planets','districts','deposits','situations','species'):checks[k+'_held']=a[k]==b[k]
p={'status':'PASS_PAID_NATIVE_MARKET_SCOPE' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'actual_trade_paid':str(paid),'actual_minerals_after':ac['effective_stockpile']['minerals'],'actual_trade_after':ac['effective_stockpile']['trade'],'actual_quote_image_sha256':f['image_sha256'],'actual_after_image_sha256':fafter['image_sha256'],'scope':'One real domestic-market purchase of1000 minerals for native trade currency. No auto-trade, energy deduction, calendar or resource grant.'};h.write_json(run/(stage+'-proof.json'),p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original market payment guard failure retained; do not buy again'
