import json,logging,shutil,sys,zipfile
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime']
import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name)
before='organic-third-marauder-withdraw-ack';stage='organic-third-marauder-loss-ack';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));eb=(user/'logs/error.log').read_bytes()
def data(name):
 with zipfile.ZipFile(run/(name+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 events={q.scalars(v)['id']:v for k,v,o in q.fields(t) if k=='player_event' and o and q.scalars(v).get('country')==0}
 return t,events
bt,bp=data(before);assert 406 in bp and q.scalars(q.block(bp[406],'scope'))['id']==1672;col=b['planets']['1672']['colony'];assert col==40
f=r.gpu_capture(stage+'-actual-option');label='\u4e00\u5b9a\u8981\u8ba9\u4ed6\u4eec\u4e3a\u6b64\u4ed8\u51fa\u4ee3\u4ef7\u3002';rows=[v for v in f['rows'] if v['text']==label and v['score']>.8];assert len(rows)==1;row=rows[0];pt=(round(sum(x[0] for x in row['box'])/4),round(sum(x[1] for x in row['box'])/4));hwnd=h.focus_pid(h.process_record(run)['pid']);desk=h.win32gui.ClientToScreen(hwnd,pt);old=h.pyautogui.PAUSE
try:
 h.pyautogui.PAUSE=0;h.pyautogui.click(*desk);h.win32api.keybd_event(0,0x01,0x0008,0);h.win32api.keybd_event(0,0x01,0x0008|h.win32con.KEYEVENTF_KEYUP,0)
finally:h.pyautogui.PAUSE=old
h.write_json(run/(stage+'-actual-choice.action.json'),{'client_point':pt,'actual_option':label,'native_event_id':406,'native_scope_planet':1672,'source_image_sha256':f['image_sha256']})
a=r.native_save(stage,b['date'],(0,));at,ap=data(stage);bc,ac=b['countries']['0'],a['countries']['0'];ea=(user/'logs/error.log').read_bytes();(run/(stage+'-error-after.log')).write_bytes(ea)
bg={k:v for k,v in b['pop_groups'].items() if v['planet']==col};ag={k:v for k,v in a['pop_groups'].items() if v['planet']==col};loss={k:bg[k]['size']-ag.get(k,{}).get('size',0) for k in bg if bg[k]['size']!=ag.get(k,{}).get('size',0)};total_loss=sum(loss.values());history_before=q.block(q.block(bt,'open_player_event_selection_history'),'selected');history_after=q.block(q.block(at,'open_player_event_selection_history'),'selected');history_gain=history_after[len(history_before.rstrip()):] if history_after.startswith(history_before.rstrip()) else ''
expected_loss=(len(loss)==1 and next(iter(loss.values()))==min(bg[next(iter(loss))]['size'],200)) or (len(loss)==2 and all(v==min(bg[k]['size'],100) for k,v in loss.items()))
checks={'same_actual_date':a['date']==b['date'],'no_new_errors':ea==eb,'only_pending406_removed':set(bp)-set(ap)=={406} and not set(ap)-set(bp),'no_new_local_pop_groups':not set(ag)-set(bg),'two_native_kill_single_pop_amounts':expected_loss,'carrier_actual_population_loss_exact':b['colonies']['40']['actual_pop_sum']-a['colonies']['40']['actual_pop_sum']==total_loss,'all_other_raw_population_groups_held':{k:v for k,v in b['pop_groups'].items() if v['planet']!=col}=={k:v for k,v in a['pop_groups'].items() if v['planet']!=col},'all_other_raw_colonies_held':{k:v for k,v in b['colonies'].items() if k!='40'}=={k:v for k,v in a['colonies'].items() if k!='40'},'all_other_jobs_held':{k:v for k,v in b['pop_jobs'].items() if v['planet']!=col}=={k:v for k,v in a['pop_jobs'].items() if v['planet']!=col}}
for k in ('effective_stockpile','research_stockpile','tech_status','variables','flags','traditions','ascension_perks','government'):checks[k+'_held']=bc[k]==ac[k]
for k in ('planets','districts','deposits','species','situations'):checks[k+'_held']=a[k]==b[k]
p={'status':'PASS_LOSS_SCOPE_PENDING_HISTORY_REVIEW' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'actual_loss':total_loss,'local_group_size_losses':loss,'raw_affected_groups_before':bg,'raw_affected_groups_after':ag,'native_country_fields_before':bc['native'],'native_country_fields_after':ac['native'],'affected_colony_before':b['colonies']['40'],'affected_colony_after':a['colonies']['40'],'raw_affected_jobs_before':{k:v for k,v in b['pop_jobs'].items() if v['planet']==col},'raw_affected_jobs_after':{k:v for k,v in a['pop_jobs'].items() if v['planet']==col},'actual_history_added_raw':history_gain,'scope':'Real existing marauder.105 two native kill_single_pop effects at physical1672/colony40; no population compensation. Human choice history requires separate non-empty structured comparison.'};h.write_json(run/(stage+'-proof.json'),p);print(json.dumps({'status':p['status'],'checks':checks,'actual_loss':total_loss,'group_size_losses':loss,'sha':a['save_sha256']}),flush=True);assert all(checks.values()),'Original native loss guard failure retained'
