import json,logging,shutil,subprocess,sys,zipfile
from decimal import Decimal as D,ROUND_DOWN
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name);before='organic-mother-mine4-ordered';stage='organic-third-postsettlement-nextmonth';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));driver=subprocess.run([sys.executable,'_runtime/heart-of-devouring/formal_native_calendar_recorded.py',before,'2303.10.02',stage,'30'],capture_output=True);(run/(stage+'-parent-driver-stdout.txt')).write_bytes(driver.stdout);(run/(stage+'-parent-driver-stderr.txt')).write_bytes(driver.stderr)
assert driver.returncode==0,'Original actual month calendar failure retained; no replay';a=json.loads((run/(stage+'.audit.json')).read_text(encoding='utf-8'));bc,ac=b['countries']['0'],a['countries']['0'];resources=('energy','minerals','food','consumer_goods','alloys','unity');balance=ac['budget_categories']['current_month']['balance'];net={k:sum((D(str(v.get(k,0))) for v in balance.values()),D(0)) for k in resources};resid={k:D(str(ac['effective_stockpile'][k]))-D(str(bc['effective_stockpile'][k]))-net[k] for k in resources};expected=dict(bc['variables']);expected.update(eep_c_remainder=0,eep_g_remainder=4,eep_chunks=36)
with zipfile.ZipFile(run/(stage+'.sav')) as z:raw=z.read('gamestate').decode('utf-8-sig')
c=q.block(raw,'construction');queue=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');ids=q.ids(q.block(queue,'items'));items=q.block(q.block(c,'item_mgr'),'items');farm=q.scalars(q.block(items,'721420313'));mine=q.scalars(q.block(items,'1241514008'));pending=[q.scalars(v) for k,v,o in q.fields(raw) if k=='player_event' and o and q.scalars(v).get('country')==0]
period=ac['budget_categories']['current_month'];ti=sum((D(str(v.get('astral_threads',0))) for v in period['income'].values()),D(0));te=sum((D(str(v.get('astral_threads',0))) for v in period['expenses'].values()),D(0));eb=(run/(stage+'-error-before.log')).read_bytes();ea=(run/(stage+'-error-after.log')).read_bytes()
checks={'actual_month_date':a['date']=='2303.10.02','no_new_errors':ea==eb,'all_six_budget_residuals_zero':all(v==0 for v in resid.values()),'exact_report_cache_updates_only':ac['variables']==expected,'EEP_notice_pending_only_removed':set(ac['flags'])==set(bc['flags'])-{'eep_notice_pending'} and all(ac['flags'][k]==bc['flags'][k] for k in ac['flags']),'native_shroud_plus3_75':D(str(a['situations']['33554438']['progress']))-D(str(b['situations']['33554438']['progress']))==D('3.75'),'native_threads_income3_upkeep0_exact':ti==3 and te==0 and D(str(ac['effective_stockpile']['astral_threads']))-D(str(bc['effective_stockpile']['astral_threads']))==3,'same_two_serial_queue_items':ids==[721420313,1241514008] and q.scalars(queue).get('simultaneous')==1,'farm_progress30_needed240':farm.get('progress')==30 and farm.get('progress_needed')==240,'mine_progress0_needed240':mine.get('progress')==0 and mine.get('progress_needed')==240,'no_early_district_completion':a['districts']['3']['level']==5 and a['districts']['2']['level']==3,'farm_mine_workforce_caps_held':a['pop_jobs']['27']['max_workforce']==1500 and a['pop_jobs']['26']['max_workforce']==600,'owned_colonies_AP_traditions_held':all(bc[k]==ac[k] for k in ('owned_colonies','ascension_perks','traditions')),'native_latent_family_held':all(a['species'][k]==b['species'][k] for k in ('102','103')),'mother_core_unique_owned':sum('eep_core' in p['flags'] for p in a['planets'].values())==1 and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'all_primary_stock_positive':all(ac['effective_stockpile'][k]>0 for k in resources)}
research={}
for k in ('physics_research','society_research','engineering_research'):
 n=sum((D(str(v.get(k,0))) for v in balance.values()),D(0));d=D(str(ac['research_stockpile'][k]))-D(str(bc['research_stockpile'][k]));research[k]={'actual_bank_delta':str(d),'net':str(n),'expected_speed_credit':str((n*D('1.13')).quantize(D('.00001'),rounding=ROUND_DOWN))}
p={'status':'PASS_SCOPED' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'actual_primary_net':{k:str(v) for k,v in net.items()},'all_primary_budget_residuals':{k:str(v) for k,v in resid.items()},'actual_stocks':ac['effective_stockpile'],'negative_primary_net':[k for k,v in net.items() if v<0],'research_observation':research,'pending_native_events':pending,'actual_report_variables':ac['variables'],'native_farm_item':farm,'native_mine_item':mine,'scope':'Actual post-settlement accounting month and serial paid-construction guard. Derived report refresh is explicit; native research observations do not imply a new grant or full civic acceptance.'};h.write_json(run/(stage+'-proof.json'),p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original post-settlement native month failure retained'
