import json,shutil,sys,zipfile
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');import audit_save as q
run=Path('_runtime/heart-of-devouring/runs/20261008T103147Z');dest=run/Path(__file__).name
if not dest.exists():shutil.copyfile(__file__,dest)
assert dest.read_bytes()==Path(__file__).read_bytes()
before='organic-psicorps-building-lastday';after='organic-psicorps-building-completed';b=json.loads((run/(before+'.audit.json')).read_text(encoding='utf-8'));a=json.loads((run/(after+'.audit.json')).read_text(encoding='utf-8'))
def raw(stem):
    with zipfile.ZipFile(run/(stem+'.sav')) as z:return z.read('gamestate').decode('utf-8-sig')
def queue(t):
    c=q.block(t,'construction');sq=q.block(q.block(q.block(c,'queue_mgr'),'queues'),'0');it=q.block(q.block(c,'item_mgr'),'items');ids=q.ids(q.block(sq,'items'))
    return ids,{str(i):q.block(it,str(i)) for i in ids}
bt,at=raw(before),raw(after);bid,bi=queue(bt);aid,ai=queue(at);bc,ac=b['countries']['0'],a['countries']['0'];bb=q.block(bt,'buildings');ab=q.block(at,'buildings');bz=q.block(bt,'zones');az=q.block(at,'zones');bids=q.ids(q.block(q.block(bz,'0'),'buildings'));aids=q.ids(q.block(q.block(az,'0'),'buildings'))
corps=[i for i in aids if q.scalars(q.block(ab,str(i))).get('type')=='building_psi_corps'];jobs=[{'id':k,**v} for k,v in a['pop_jobs'].items() if v['planet']==0 and v['type']=='telepath'];soldiers=[{'id':k,**v} for k,v in a['pop_jobs'].items() if v['planet']==0 and v['type']=='soldier']
pending=[q.scalars(v) for k,v,o in q.fields(at) if k=='player_event' and o and q.scalars(v).get('country')==0]
checks={'actual_date':a['date']=='2306.09.02','native_before479_of480':q.scalars(bi['167772186']).get('progress')==479,'native_only_corps_order_removed':bid==[167772186,167772187,218103840] and aid==[167772187,218103840],'later_two_orders_raw_held':all(ai.get(str(i))==bi[str(i)] for i in aid),'native_one_exact_position1_psi_corps':len(corps)==1 and q.scalars(q.block(ab,str(corps[0]))).get('position')==1,'native_stronghold_absent_in_zone0':not any(q.scalars(q.block(ab,str(i))).get('type')=='building_stronghold' for i in aids),'only_old_stronghold_slot_replaced':len(aids)==len(bids)==6 and set(aids)==(set(bids)-{50331775})|set(corps),'all_other_seven_original_buildings_raw_held':all(q.block(ab,str(i))==q.block(bb,str(i))!='' for i in [0,3,16777262,50331657,248,2,237]),'archive_zone_raw_held':q.block(az,'1')==q.block(bz,'1'),'native_telepath_capacity200':len(jobs)==1 and jobs[0]['max_workforce']==200,'native_telepath_workforce200':len(jobs)==1 and jobs[0]['workforce']==200,'native_mother_soldier_workforce0':all(v['workforce']==0 and v['max_workforce']==0 for v in soldiers),'native_stage2_and_bounded_single_month_progress':a['situations']['33554438']['stage']==1 and a['situations']['33554438']['progress'] in [502,505.75],'earned_capacity12_held':a['planets']['7']['variables']['eep_capacity_value']==12,'mother_unique_core_owned':sum('eep_core' in v['flags'] for v in a['planets'].values())==1 and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'no_new_errors':(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes(),'no_pending_native_events':not pending,'latent_family_definitions_held':all(b['species'][k]==a['species'][k] for k in ['102','103']),'EEP_variables_held':bc['variables']==ac['variables'],'EEP_flags_held':bc['flags']==ac['flags'],'AP_traditions_government_owned_colonies_held':all(bc[k]==ac[k] for k in ['ascension_perks','traditions','government','owned_colonies']),'mine4_and_farm6_held':a['districts']['2']['level']==4 and a['districts']['3']['level']==6,'miner800_farmer1800_held':a['pop_jobs']['26']['max_workforce']==800 and a['pop_jobs']['27']['max_workforce']==1800,'housing_and_amenities_positive':a['colonies']['0']['free_housing']>0 and a['colonies']['0']['free_amenities']>0,'all_primary_actual_stocks_positive':all(ac['effective_stockpile'][k]>0 for k in ['energy','minerals','food','consumer_goods','alloys','unity'])}
p={'status':'PASS_NATIVE_480_DAY_CORPS_COMPLETION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'native_queue_before':bid,'native_queue_after':aid,'actual_corps_ids':corps,'native_corps_raw':[q.block(ab,str(i)) for i in corps],'native_telepath_jobs':jobs,'native_soldier_jobs':soldiers,'actual_colony_before':b['colonies']['0'],'actual_colony_after':a['colonies']['0'],'native_country_military_before':bc['native'],'native_country_military_after':ac['native'],'native_shroud_before':b['situations']['33554438'],'native_shroud_after':a['situations']['33554438'],'scope':'Real paid480-day Stronghold replacement,200 telepath slots/workforce and actual soldier/naval changes. Native monthly Shroud recovery is checked separately; no whole psionic or civic acceptance.'}
out=run/(after+'-construction-proof.json');assert not out.exists();out.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8');print(json.dumps(p),flush=True);assert all(checks.values()),'Original completion FAIL retained; stop next calendar'
