import json,logging,re,shutil,subprocess,sys
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime']
import runtime as r
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name)
calendar=Path('_runtime/heart-of-devouring/formal_production_native_calendar.py');start='organic-shroud-unravel-nextmonth';b=json.loads((run/(start+'.audit.json')).read_text(encoding='utf-8'));baseline=b;output=run/'organic-shroud-unravel-years-result.json';assert not output.exists();result={'status':'RUNNING','stages':[],'scope':'At most five actual 360-day native years; stop before projected astral reserve below 80. Not full shroud or civic acceptance.'};h.write_json(output,result)
resources=('energy','minerals','food','consumer_goods','alloys','unity')
def net(country,k):return sum((D(str(v.get(k,0))) for v in country['budget_categories']['current_month']['balance'].values()),D(0))
for i in range(1,6):
 bc=b['countries']['0'];thread_stock=D(str(bc['effective_stockpile']['astral_threads']));thread_net=net(bc,'astral_threads')
 if thread_stock+12*thread_net<80:
  result.update(status='STOP_THREAD_RESERVE_BEFORE_ADVANCE',current_stage=start,current_save_sha256=b['save_sha256'],thread_stock=str(thread_stock),thread_monthly_net=str(thread_net),projected_12_month_stock=str(thread_stock+12*thread_net));h.write_json(output,result);print(json.dumps(result),flush=True);break
 year,month,day=[int(v) for v in b['date'].split('.')];date=f'{year+1:04d}.{month:02d}.{day:02d}';stage=f'organic-shroud-unravel-year-{year+1}'
 driver=subprocess.run([sys.executable,str(calendar),start,date,stage,'360'],capture_output=True,text=True,encoding='utf-8');(run/(stage+'-driver-output.txt')).write_text(driver.stdout+driver.stderr,encoding='utf-8')
 if driver.returncode:
  result.update(status='FAILED_STAGE',failed_stage=stage,original_driver_returncode=driver.returncode);h.write_json(output,result);print(json.dumps(result),flush=True);raise RuntimeError('Original annual driver failure retained; do not repeat calendar days')
 a=json.loads((run/(stage+'.audit.json')).read_text(encoding='utf-8'));ac=a['countries']['0'];state=json.loads((run/(stage+'-state.json')).read_text(encoding='utf-8'));eb=(run/(stage+'-error-before.log')).read_bytes();ea=(run/(stage+'-error-after.log')).read_bytes();new_errors=ea[len(eb):] if ea.startswith(eb) else ea;after_net={k:net(ac,k) for k in resources};s=a['situations']['33554438']
 checks={'expected_actual_date':a['date']==date,'EEP_ledger_held':bc['variables']==ac['variables'],'EEP_flags_held':bc['flags']==ac['flags'],'existing_AP_traditions_held':bc['ascension_perks']==ac['ascension_perks'] and bc['traditions']==ac['traditions'],'owned_colony_ids_held':bc['owned_colonies']==ac['owned_colonies'],'native_founder_held':bc['native']['founder_species_ref']==ac['native']['founder_species_ref'],'native_family_templates_held':all(b['species'][k]==a['species'][k] for k in ('102','103')),'true_research_bank_available':ac['research_stockpile'] is not None,'primary_stocks_positive':all(ac['effective_stockpile'][k]>0 for k in resources),'astral_reserve_at_least_80':ac['effective_stockpile']['astral_threads']>=80,'mother_unique_core_owned':sum('eep_core' in p['flags'] for p in a['planets'].values())==1 and 'eep_core' in a['planets']['7']['flags'] and a['planets']['7']['owner']==a['planets']['7']['controller']==0,'native_theory_completed':'tech_psionic_theory' in ac['completed_technologies'],'shroud_same_approach_stage_zero':s['approach']=='approach_situation_breach_shroud_unravel_thread' and s['stage']==0,'shroud_progress_increased':s['progress']>b['situations']['33554438']['progress'],'no_new_EEP_script_errors':not re.search(rb'eep_',new_errors,re.I)}
 proof={'status':'PASS_SCOPED' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'date':a['date'],'actual_shroud':s,'actual_stocks':ac['effective_stockpile'],'current_primary_net':{k:str(v) for k,v in after_net.items()},'new_error_bytes':state['new_error_bytes'],'negative_primary_net_observed':[k for k,v in after_net.items() if v<0],'scope':'One actual year, native research and population continue; not full shroud, 20-year economic acceptance, or a resource grant.'};h.write_json(run/(stage+'-proof.json'),proof);result['stages'].append({'stage':stage,'proof':proof});h.write_json(output,result);print(json.dumps({'stage':stage,'checks':checks,'stocks':ac['effective_stockpile'],'shroud':s,'current_primary_net':proof['current_primary_net'],'new_error_bytes':state['new_error_bytes']}),flush=True)
 if not all(checks.values()):result.update(status='FAILED_GUARDS',failed_stage=stage);h.write_json(output,result);raise RuntimeError('Original annual guard failure retained')
 b=a;start=stage
 if any(v<0 for v in after_net.values()):result.update(status='STOP_NEGATIVE_PRIMARY_NET',current_stage=start,current_save_sha256=b['save_sha256']);h.write_json(output,result);print(json.dumps(result),flush=True);break
else:result.update(status='FIVE_YEARS_OBSERVED',current_stage=start,current_save_sha256=b['save_sha256']);h.write_json(output,result)
