"""Read-only exact native repeated key/value growth pairs; prior failures retained."""
import json,logging,shutil,sys,zipfile
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime','--vanilla'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(Path(__file__),run/Path(__file__).name)
pop=json.loads((run/'preftl-control-population-supplement.json').read_text('utf-8'));err=json.loads((run/'preftl-control-error-reproduction-proof.json').read_text('utf-8'))
with zipfile.ZipFile(run/'preftl-control-event.sav') as z:t=z.read('gamestate').decode('utf-8-sig')
col=q.block(q.block(t,'colony'),'8');growth=q.block(col,'current_month_growth_data');raw=q.block(growth,'current_month_growth_details');fields=[(k,q.unquote(v),o) for k,v,o in q.fields(raw)]
checks={'bound_population9_only_OTHER_parser_FAIL_other8_true':pop['status']=='FAIL' and len(pop['checks'])==9 and [k for k,v in pop['checks'].items() if not v]==['native_colony_OTHER100_observed'], 'bound_error16_only_population_FAIL_other15_true':err['status']=='FAIL' and len(err['checks'])==16 and [k for k,v in err['checks'].items() if not v]==['target29_native_population200_to300'], 'bound_same_original_SHA_pair':err['before_sha256']==pop['before_sha256']==h.sha256(run/'preftl-control-loaded.sav') and err['after_sha256']==pop['after_sha256']==h.sha256(run/'preftl-control-event.sav'), 'exact_original_ordered_scalar_growth_pairs':fields==[('key','GROWTH_CAT_OTHER',False),('value',100,False),('key','GROWTH_CAT_PROMOTION',False),('value',0,False)], 'actual_enabled_mods_empty':m['enabled_mods']==json.loads((user/'dlc_load.json').read_text('utf-8'))['enabled_mods']==[]}
p={'status':'PASS_SCOPED_NO_MOD_PRE_FTL_REPRODUCTION_SUPPLEMENT' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':pop['before_sha256'],'after_sha256':pop['after_sha256'],'raw_growth_details':raw,'ordered_fields':fields,'scope':'Exact native growth100 pairs combined with original15 valid error checks and original8 valid population checks. Both original failures retained. Same error needs no enabled EEP scripts; not clean vanilla-origin world generation, load-baseline certification or production natural route pass.'}
out=run/'preftl-control-growth-pairs-supplement.json';assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original growth-pair supplement FAIL retained'
