"""Independent raw Colony8/group population proof; original cached-country FAIL retained."""
import json,logging,shutil,sys,zipfile
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime','--vanilla'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(Path(__file__),run/Path(__file__).name)
pre=json.loads((run/'preftl-control-error-reproduction-proof.json').read_text('utf-8'))
def raw(stem):
 with zipfile.ZipFile(run/(stem+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 roots={k:v for k,v,o in q.fields(t) if o};c=q.scalars(q.block(roots['country'],'29'));col=q.block(roots['colony'],str(c['capital']));carrier=q.scalars(q.block(col,'carrier'));p=q.scalars(q.block(q.block(roots['planets'],'planet'),str(carrier['reference'])));groups={str(i):q.scalars(q.block(roots['pop_groups'],str(i))) for i in q.ids(q.block(col,'pop_groups'))}
 return c,q.scalars(col),p,groups,q.block(col,'current_month_growth_data')
b,bc,bp,bg,bgrowth=raw('preftl-control-loaded');a,ac,ap,ag,agrowth=raw('preftl-control-event');other=[q.scalars(v)['value'] for k,v,o in q.fields(q.block(agrowth,'current_month_growth_details')) if o and q.scalars(v).get('key')=='GROWTH_CAT_OTHER']
checks={'bound_original16_only_population_FAIL_and_other15_true':pre['status']=='FAIL' and len(pre['checks'])==16 and [k for k,v in pre['checks'].items() if not v]==['target29_native_population200_to300'], 'original_SHA_pair':h.sha256(run/'preftl-control-loaded.sav')==pre['before_sha256'] and h.sha256(run/'preftl-control-event.sav')==pre['after_sha256'], 'actual_no_mod_config':m['enabled_mods']==json.loads((user/'dlc_load.json').read_text('utf-8'))['enabled_mods']==[], 'native_capital_Col8_carrier1485_ownership':b['capital']==a['capital']==8 and bp['colony']==ap['colony']==8 and bp['owner']==ap['owner']==bp['controller']==ap['controller']==29, 'raw_group_actual_sum200_to300':sum(g['size'] for g in bg.values())==200 and sum(g['size'] for g in ag.values())==300 and all(g['planet']==8 for g in [*bg.values(),*ag.values()]), 'exact_raw_groups_before_after':{k:g['size'] for k,g in bg.items()}=={'32':200} and {k:g['size'] for k,g in ag.items()}=={'32':100,'69':100,'70':100}, 'colony_counter_tracks_actual200_to300':bc['num_sapient_pops']==200 and ac['num_sapient_pops']==300, 'country_counter_cache200_held':b['num_sapient_pops']==a['num_sapient_pops']==200, 'native_colony_OTHER100_observed':other==[100]}
p={'status':'PASS_SCOPED_NO_MOD_PRE_FTL_POPULATION_SUPPLEMENT' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':pre['before_sha256'],'after_sha256':pre['after_sha256'],'actual_groups_before_after':[bg,ag],'country_cache_before_after':[b['num_sapient_pops'],a['num_sapient_pops']],'scope':'Independent raw native population proof joined to original15 successful no-mod error reproduction checks. Original16-check population FAIL retained; no event replay/calendar or clean vanilla-generation/Mod route pass claim.'}
out=run/'preftl-control-population-supplement.json';assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Independent population supplement FAIL retained'
