"""Read-only scoped reproduction of native country29 preFTL government error."""
import json,logging,re,shutil,sys,zipfile,hashlib
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime','--vanilla'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(Path(__file__),run/Path(__file__).name)
def read(stem):
 a=json.loads((run/(stem+'.audit.json')).read_text('utf-8'))
 with zipfile.ZipFile(run/(stem+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 return a,{k:v for k,v,o in q.fields(q.block(t,'country')) if o}
b,br=read('preftl-control-loaded');a,ar=read('preftl-control-event');bc,ac=q.scalars(br['29']),q.scalars(ar['29']);bg,ag=q.block(br['29'],'government'),q.block(ar['29'],'government')
pre=json.loads((run/'preftl-control-loaded-proof.json').read_text('utf-8'));obs=json.loads((run/'preftl-control-event-observation.json').read_text('utf-8'))
prod=Path(json.loads(Path(m['production_pointer_backup']).read_text('utf-8'))['artifact_dir'])
pb=(prod/'terravore-second-psionic-wait-year1-error-before.log').read_bytes();pa=(prod/'terravore-second-psionic-wait-year1-error-after.log').read_bytes();cb=(run/'preftl-control-event-error-before.log').read_bytes();ca=(run/'preftl-control-event-error-after.log').read_bytes();pd,cd=pa[len(pb):],ca[len(cb):]
normalize=lambda v:re.sub(rb'\[\d{2}:\d{2}:\d{2}\]',b'[TIME]',v)
checks={'actual_enabled_mods_empty':m['enabled_mods']==json.loads((user/'dlc_load.json').read_text('utf-8'))['enabled_mods']==[], 'bound_original_load6_PASS':pre['status']=='PASS_PRE_FTL_CONTROL_LOAD_ONLY' and len(pre['checks'])==6 and all(pre['checks'].values()) and pre['after_sha256']==b['save_sha256'], 'original_SHA_pair':h.sha256(run/'preftl-control-loaded.sav')==b['save_sha256'] and h.sha256(run/'preftl-control-event.sav')==a['save_sha256'], 'one_exact_native_event_receipt':obs['command']=='event preftl.199 29' and obs['before_sha256']==b['save_sha256'] and obs['after_sha256']==a['save_sha256'], 'same_actual_date':b['date']==a['date']=='2233.09.01', 'target29_original_stone_to_bronze':bc['type']==ac['type']=='primitive' and bc['preftl_age']=='stone_age' and ac['preftl_age']=='bronze_age', 'target29_original_government_raw_held':bg==ag, 'target29_original_hive_post_apocalyptic':q.scalars(ag)['authority']=='auth_hive_mind' and q.scalars(ag)['origin']=='origin_post_apocalyptic', 'target29_native_population200_to300':bc['num_sapient_pops']==200 and ac['num_sapient_pops']==300 and b['colonies']['8']['actual_pop_sum']==200 and a['colonies']['8']['actual_pop_sum']==300, 'all_other_countries_raw_held':set(br)==set(ar) and all(ar[k]==v for k,v in br.items() if k!='29'), 'country0_actual_stocks_held':b['countries']['0']['effective_stockpile']==a['countries']['0']['effective_stockpile'], 'country0_actual_population_held':b['colonies']['0']['actual_pop_sum']==a['colonies']['0']['actual_pop_sum'], 'original_error_prefixes_preserved':pa.startswith(pb) and ca.startswith(cb), 'exact972_error_increment_each':len(pd)==len(cd)==972, 'entire_error_body_same_after_timestamp_normalization':normalize(pd)==normalize(cd), 'exact_two_native_errors_no_unrelated_increment':cd.count(b'government_restrictions_solver.cpp:1452')==cd.count(b'effect_impl.cpp:12240')==1 and b'pre_ftl_scripted_effects.txt:1767' in cd and b'first_contact_dlc_situation_events.txt line: 534' in cd}
sources=[Path('C:/SteamLibrary/steamapps/common/Stellaris/common/scripted_effects/pre_ftl_scripted_effects.txt'),Path('C:/SteamLibrary/steamapps/common/Stellaris/events/first_contact_dlc_situation_events.txt'),Path('C:/SteamLibrary/steamapps/common/Stellaris/common/governments/civics/00_origins.txt')]
proof={'status':'PASS_SCOPED_NO_MOD_PRE_FTL_ERROR_REPRODUCTION' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'production_error_delta_sha256':hashlib.sha256(pd).hexdigest(),'control_error_delta_sha256':hashlib.sha256(cd).hexdigest(),'error_increment_bytes':len(cd),'native_sources':[{'path':str(s),'sha256':h.sha256(s)} for s in sources],'original_production_run':str(prod),'scope':'Same native error reproduced without enabled mods from unchanged native country29 in original-byte Mod-derived world by one explicit preftl.199 call. Proves active EEP scripts are unnecessary for this error; does not prove clean vanilla-origin world generation, certify load-baseline EEP missing-definition warnings or pass the original yearly no-new-error check.'}
out=run/'preftl-control-error-reproduction-proof.json';assert not out.exists();h.write_json(out,proof);print(json.dumps(proof),flush=True);assert all(checks.values()),'Original no-mod control FAIL retained'
