import hashlib,json
from pathlib import Path
ROOT=Path('eat_everything_origin');BASE=ROOT/'docs/evidence/runtime-development'
def ref(run,name):return (BASE/run/name).relative_to(ROOT).as_posix()
R='20261008T003349Z';F='20261006T232907Z';N='20261007T031421Z';C='20261007T100241Z';D='20261007T203412Z'
spec={
1:('Legal natural Scorched Hive initial state and rewards; common non-origin/foreign isolation and final production initialization.',[(F,'findings.json'),('20261007T215509Z','rc8-nonqualified-own-capital-proof.json'),(R,'rc9-native-creation-refusals-proof.json')]),
2:('Scorched Hive legal entrance; native ordinary and Assimilator disallowed creation UI. Other open routes remain incomplete.',[(R,'rc9-native-creation-refusals-proof.json'),(F,'findings.json')]),
3:('Native real ark/star and ground combat refusal; shared object eligibility, no seed/resources moved on refusal.',[('20261007T131538Z','rc5-real-ark-source-core-native-ui-proof.json'),('20261007T131538Z','rc5-real-star-native-refusal-proof.json'),(N,'native-ground-combat-start-refusal-restore-proof.json'),('20261006T224056Z','findings.json'),(D,'rc7-zero-query-guard-partial-proof.json')]),
4:('Actual 100 founder-pop transfer, conserved country population, insufficient-founder refusal; current native template preservation.',[('20261008T074219Z','rc9-missing-shroud-compatibility-proof.json'),(D,'rc7-zero-query-guard-partial-proof.json'),('20261007T134815Z','rc5-verified-current-main-old-template-return-foreign-proof.json'),('20261006T192819Z','findings.json')]),
6:('Controlled triple Q20 Scorched Hive ledger plus natural Q16 and current native Q8/Q12 final settlement. Controlled endpoints do not prove calendar.',[(F,'findings.json'),(R,'rc9-stage2-natural-source12-calendar-settlement-proof.json'),('20261008T074219Z','rc9-missing-shroud-compatibility-proof.json')]),
7:('Common native Q3/Q5 remainder subcases and controlled Scorched Hive triple Q20; native current small-world capacity/pop increment and replay.',[('20261006T192819Z','findings.json'),(F,'findings.json'),('20261008T074219Z','rc9-missing-shroud-compatibility-proof.json')]),
9:('Common native mid47 cancellation/restart, old damage and fixed-query/zero guard; no early payout.',[('20261007T154144Z','rc6-natural-mid47-cancel-old-damage-restart-q14-proof.json'),(D,'rc7-zero-query-guard-partial-proof.json')]),
10:('Common actual two qualified owners, distinct systems/cores and legal new-owner settlement; not full Purifier route acceptance.',[(D,'rc7-dual-owner-separate-system-settlement-proof.json'),(D,'rc7-dual-separate-outpost-native-owner-proof.json')]),
11:('Scorched Hive actual waiting endpoint, native extinction purge, reload and no duplicate completion.',[(R,'rc9-focus-wait39-reload-proof.json'),(R,'rc9-focus-wait39-replay-proof.json'),(R,'rc9-focus-native-purge-final-proof.json'),(R,'rc9-focus-native-purge-final-replay-proof.json')]),
12:('Actual bound-core transfer/retake, ownership payroll isolation and permanent-death negative with active tasks; no replacement capacity.',[('20261007T145123Z','rc6-native-court-transfer-retake-reload-proof.json'),('20261007T145123Z','rc6-new-court-active-task-permanent-death-proof.json'),(R,'rc9-permanent-core-death-repair-negative-proof.json')]),
13:('Common real AI migrated capital15 while bound core8 receives native return/manufacture; distinct cores and recoverable physical capacity, no opening reward duplication.',[('20261007T154144Z','rc6-real-ai-native-population-bound-core-proof.json'),('20261007T154144Z','rc6-natural48-ai-five-replays-strict-proof.json'),(D,'rc7-dual-owner-separate-system-settlement-proof.json'),('20261007T145123Z','rc6-native-court-transfer-retake-reload-proof.json')]),
14:('Native waiting/reload/completion-message/repeated-callback states; exact all-resource, population and receipt conservation.',[(R,'rc9-focus-wait39-reload-proof.json'),(R,'rc9-focus-native-purge-final-replay-proof.json'),(R,'rc9-stage2-native-first-queen-reload-proof.json'),(R,'rc9-stage2-native-first-queen-five-replays-proof.json'),(D,'rc7-dual-core-reports-notice-ten-callbacks-proof.json')]),
15:('Common controlled same-country two Q20 same-day receipt subcase, not natural simultaneous conquest; triple Scorched Hive payout and current shared replay controls.',[('20261006T192819Z','findings.json'),(F,'findings.json'),(D,'rc7-dual-core-reports-notice-ten-callbacks-proof.json')]),
16:('Current actual bombardment, return-abandonment, ordinary purge and native Star Eater world destruction; day/month and completion replays do not grant EEP rewards.',[(R,'rc9-external-abandon-completed-negative-replay-proof.json'),(R,'rc9-external-purge-completed-negative-replay-proof.json'),(R,'rc9-external-star-real-detonation-proof.json'),(R,'rc9-external-star-completed-negative-replay-proof.json'),(R,'rc9-external-bombard-real-clearing-proof.json'),(R,'rc9-external-bombard-completed-negative-replay-proof.json')]),
17:('Natural Scorched Hive paid district/building workforce and housing; current paid Hive-world industry build completion; capacity alone creates no districts.',[(F,'findings.json'),(R,'rc9-native-heavy-industry-paid-scoped-proof.json'),(R,'rc9-native-heavy-industry-completed-proof.json')]),
18:('Common native current founder template, preserved old subtemplate and foreign shared-template isolation; natural Hive psionic workforce completion.',[('20261007T134815Z','rc5-verified-current-main-old-template-return-foreign-proof.json'),(N,'native-psi-final-ritual-completed.audit.json'),('20261007T154144Z','rc6-mixed-same-country-five-replays-all-foreign-proof.json')]),
19:('Natural legal Scorched Hive full Shroud completion and two independently missing-DLC basic loops/AP previews; no other-route natural ascension claim.',[(N,'native-psi-queen-reload-calendar-replay-proof.json'),(N,'native-psi-final-ritual-completed.audit.json'),('20261008T063908Z','rc9-missing-nemesis-compatibility-proof.json'),('20261008T074219Z','rc9-missing-shroud-compatibility-proof.json')]),
20:('Common organic Hive same-job/pop additive court income and untouched inputs/non-job income; actual Scorched Hive native employment and ownership salary isolation.',[('20261006T164008Z','findings.json'),(F,'findings.json'),('20261007T145123Z','rc6-native-court-transfer-retake-reload-proof.json')]),
21:('Natural legal Nemesis stages2/3/4, actual paid mineral hulls, zero-price exact-slot refits, dock/space/overcap upkeep; missing Nemesis denies AP.',[(R,'rc9-stage2-natural-source12-calendar-settlement-proof.json'),(N,'native-mineral-corvette-order-proof.json'),(N,'native-mineral-corvette-calendar-completion-proof.json'),(N,'native-mineral-corvette-upkeep-movement-proof.json'),(N,'native-mineral-corvette-refit-proof.json'),(N,'native-mineral-destroyer-order-upkeep-overcap-corrected-proof.json'),(C,'rc4-cruiser-native-payment-eight-built-overcap-proof.json'),(C,'rc4-cruiser-native-dock-undock-underlimit-exact-value-row-proof.json'),(C,'rc4-cruiser-native-eight-zero-price-exact-component-slot-refit-proof.json'),('20261008T063908Z','rc9-missing-nemesis-compatibility-proof.json')]),
22:('Native natural Q18/Q23 and current Q12 real world-menace objective exactly once, with completion replay and ordinary-war controls.',[(N,'native-world18-crisis3-settlement-proof.json'),(N,'native-crisis3-queen-reload-replay-scoped-proof.json'),(C,'rc4-natural-q23-stage4-first-notice-readonly-proof.json'),(R,'rc9-stage2-natural-source12-calendar-settlement-proof.json'),(R,'rc9-stage2-native-first-queen-five-replays-proof.json')]),
23:('Controlled common Terminator 1/10/100 world pressure and current C4000/D1002 native UI first/repeat/stable reload. Not natural Hive high-pop affordability.',[('20261006T192819Z','findings.json'),(R,'rc9-highcap-native-current-report-pending-readonly-proof-v2.json'),(R,'rc9-highcap-native-repeat-report-pending-readonly-proof-v2.json'),(R,'rc9-highcap-native-stable-report-reloaded-readonly-proof-v3.json')]),
24:('Scorched Hive native volcanic jobs, daily bombardment unity/purge, actual 20-year paid Hive-world conversion and one core deposit. Machine worlds deferred.',[(F,'findings.json'),(R,'rc9-external-bombard-daily-unity-proof.json'),(R,'rc9-external-bombard-real-clearing-proof.json'),(R,'rc9-natural-terraform-checkpoints-6-2319-10-22-proof.json'),(R,'rc9-old-missing-core-native-month-proof.json')]),
25:('Actual no-mod control and matched-world0/1/10/50 task timing/CPU/save/logs; both competing decision load orders. Single-sample performance, not zero-cost or universal compatibility.',[('20261007T193619Z','rc6-shared-world-performance-proof.json'),('20261007T201344Z','conflict-eep-first-actual-source-route-proof.json'),('20261007T202451Z','conflict-eep-last-route-proof.json')]),
26:('Natural Scorched Hive truce2253 and uninterrupted peace to2270 preserve C/G16 D6 made200; positive main-resource net while volatile motes remain negative.',[(F,'findings.json')]),
27:('Common unchanged Q formula natural Q15/20/25 at36/48/60 effective months from Scorched ordinary fixture; focus natural Q16/18/23 at39/44/56 and current Q8 at20. Does not claim separate focus Q20 natural campaign or true no-mod117/118 completion.',[('20261006T224056Z','findings.json'),(F,'findings.json'),(N,'native-world18-crisis3-settlement-proof.json'),(C,'rc4-native-gui-and-natural-q23-progress-proof.json'),('20261008T074219Z','rc9-missing-shroud-compatibility-proof.json')]),
28:('Actual separate qualified countries/cores and unchanged legal ruler/government/founder; natural focus Queen identity. Other governments full narrative combinations deferred.',[(D,'rc7-dual-owner-separate-system-settlement-proof.json'),(D,'rc7-dual33-native-report-reload-control-proof.json'),(F,'findings.json')]),
29:('Actual focus report budget-history-isolated strict58, dual independent reports117, nonqualified hidden37, current highcap51 and final production GUI first/repeat.',[(C,'rc4-native-audience-budget-history-isolated-readonly-proof.json'),(D,'rc7-dual-core-reports-notice-ten-callbacks-proof.json'),('20261007T215509Z','rc8-nonqualified-own-capital-proof.json'),(R,'rc9-highcap-native-stable-report-reloaded-readonly-proof-v3.json')]),
30:('Common controlled exact thresholds0/19/20/59/60/199/200, focus controlled threshold merging and both current natural Q8 first notice; no economic award from message/report.',[('20261006T164008Z','findings.json'),(F,'findings.json'),('20261008T063908Z','rc9-missing-nemesis-compatibility-proof.json'),('20261008T074219Z','rc9-missing-shroud-compatibility-proof.json')]),
31:('Natural legal full Shroud and mineral stage2/3/4 Queen notifications, pending/reloaded/normal ACK/replay; missing-DLC prevents corresponding completion notice.',[(N,'native-psi-queen-reload-calendar-replay-proof.json'),(R,'rc9-stage2-native-first-queen-reload-proof.json'),(R,'rc9-stage2-native-first-queen-ack-proof.json'),(N,'native-crisis3-queen-reload-replay-scoped-proof.json'),(C,'rc4-natural-q23-stage4-first-notice-readonly-proof.json'),(C,'rc4-stage4-native-reloaded-confirm-five-callbacks-proof.json'),('20261008T063908Z','rc9-missing-nemesis-compatibility-proof.json'),('20261008T074219Z','rc9-missing-shroud-compatibility-proof.json')]),
32:('Actual temporary original throne transfer/retake and notice/blocked tasks once; permanent death52/31 and current repair-negative no backup throne.',[('20261007T145123Z','rc6-native-court-transfer-retake-reload-proof.json'),('20261007T145123Z','rc6-new-court-active-task-permanent-death-proof.json'),('20261007T134815Z','rc5-active-task-permanent-core-death-exact-native-assembly-proof.json'),(R,'rc9-permanent-core-death-repair-negative-proof.json')]),
33:('Independent narrative and economic receipts across dual-country callbacks, natural peace, stage2/3/4 normal acknowledgements and no repeated awards.',[(D,'rc7-dual-core-reports-notice-ten-callbacks-proof.json'),(F,'findings.json'),(R,'rc9-stage2-native-first-queen-five-replays-proof.json'),(N,'native-crisis3-queen-reload-replay-scoped-proof.json'),(C,'rc4-stage4-native-reloaded-confirm-five-callbacks-proof.json')]),
}
assert len(spec)==31
cases={};review=[];missing=[]
for number,(scope,items) in spec.items():
 entries=[]
 for run,name in items:
  path=ref(run,name);p=ROOT/path
  if not p.is_file():missing.append(path);continue
  raw=p.read_bytes();d=json.loads(raw.decode('utf-8-sig'));status=d.get('status','NATIVE_AUDIT');review.append({'case':f'EAT-{number:02}','path':path,'source_status':status})
  assert status!='FAIL',(number,path)
  entries.append({'path':path,'sha256':hashlib.sha256(raw).hexdigest()})
 cases[f'EAT-{number:02}']={'status':'REVIEWED_SCOPE_AWAITING_PRODUCTION_SMOKE','scope':'scorched_hive_and_shared_mechanisms','actual_scope':scope,'evidence':entries}
for n in [5,8]:cases[f'EAT-{n:02}']={'status':'NOT_APPLICABLE','scope':'scorched_hive_and_shared_mechanisms','reason':'Scorched Hive uses the generic route; vanilla Terravore random yields and mixed Terravore route are deferred, not passed.'}
out=Path('_runtime/heart-of-devouring/first-release-matrix-draft.json');out.write_text(json.dumps({'status':'WAIT_PRODUCTION_SMOKE','cases':cases,'source_review':review,'missing':missing},indent=2)+'\n',encoding='utf-8')
print(json.dumps({'cases':len(cases),'references':len(review),'missing':missing},indent=2));assert not missing
