import hashlib,json,logging,shutil,sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime','--vanilla']
import runtime as r
from postrelease_vanilla_raw_source import inspect
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();assert m['enabled_mods']==[]
shutil.copyfile(Path(__file__),run/Path(__file__).name)
def read(stage):return json.loads((run/(stage+'.audit.json')).read_text(encoding='utf-8'))
ack=read('postvanilla-normal-ack-retry');day=read('postvanilla-normal-next-day');month=read('postvanilla-normal-next-month');fast=read('postvanilla-q20-m119')
checks={}
for label,a in [('day',day),('month',month)]:
 c=a['countries']['0'];raw=inspect(Path(a['save']));state=json.loads((run/('postvanilla-normal-next-'+label+'-state.json')).read_text(encoding='utf-8'))
 checks.update({label+'_source_shattered':raw['source']['planet_class']=='pc_shattered',label+'_source_unowned':'owner' not in raw['source'],label+'_source_empty':state['source_population']==0,label+'_no_live_native_task':not any(s.get('type')=='situation_terravore_consume_planet' and s.get('killed')!='yes' for s in a['situations'].values()),label+'_no_pending_completion':not any(e.get('event')=='colony.185' for e in raw['player_events']),label+'_no_EEP_variables':c['variables']=={},label+'_no_EEP_flags':c['flags']=={},label+'_AP_empty':c['ascension_perks']==[],label+'_new_error_zero':state['new_error_bytes']==0})
checks.update({'actual_next_day':day['date']=='2209.11.02','actual_next_month':month['date']=='2209.12.02','day_all_stock_same':ack['countries']['0']['stockpile']==day['countries']['0']['stockpile'],'day_actual_population_same':ack['colonies']['0']['actual_pop_sum']==day['colonies']['0']['actual_pop_sum']==6359,'month_native_population6365':month['colonies']['0']['actual_pop_sum']==6365,'two_branches_month_stock_same':month['countries']['0']['stockpile']==fast['countries']['0']['stockpile'],'two_branches_month_population_same':month['colonies']['0']['actual_pop_sum']==fast['colonies']['0']['actual_pop_sum']})
budget={};bc=day['countries']['0'];ac=month['countries']['0']
for res in ['energy','minerals','alloys','unity','influence','trade']:
 b=ac['budget_categories']['current_month'];income=sum(x.get(res,0) for x in b['income'].values());expense=sum(x.get(res,0) for x in b['expenses'].values());delta=ac['stockpile'].get(res,0)-bc['stockpile'].get(res,0);residual=round(delta-income+expense,8);budget[res]={'actual_delta':round(delta,8),'native_income':round(income,8),'native_expenses':round(expense,8),'residual':residual};checks['next_month_'+res+'_native_budget_only']=abs(residual)<.00001
assert all(checks.values()),checks
h.write_json(run/'postvanilla-native-next-day-month-no-repeat-proof.json',{'status':'PASS_SCOPED','checks':checks,'ack_sha256':ack['save_sha256'],'day_sha256':day['save_sha256'],'month_sha256':month['save_sha256'],'budget_observations':budget,'scope':'Actual next day/month after native human completion option; no repeat material rewards, native stock/population retained. Branch equality is limited to observed stocks and population.'})
index=json.loads((run/'postvanilla-checkpoint-source-index.json').read_text(encoding='utf-8'));stable=json.loads((run/'postvanilla-stable-retry-proof.json').read_text(encoding='utf-8'));human=json.loads((run/'postvanilla-native-completion-ack-readonly-proof.json').read_text(encoding='utf-8'));assert stable['status']==human['status']=='PASS_SCOPED'
error=(user/'logs/error.log').read_bytes()
files=['postvanilla-original-initial-proof.json','postvanilla-single-source-proof.json','postvanilla-native-begin-proof.json','postvanilla-checkpoint-source-index.json','postvanilla-stable-retry-proof.json','postvanilla-native-completion-ack-readonly-proof.json','postvanilla-native-next-day-month-no-repeat-proof.json','postvanilla-native-random-award-budget-observations-v2.json','postvanilla-normal-endpoint-proof.json','postvanilla-first-reload-proof.json','postvanilla-normal-ack-retry-proof.json','postvanilla-boundary-driver-result.json','postvanilla-boundary-driver-v2-result.json']
proof={'status':'PASS_SCOPED','run_id':run.name,'actual_enabled_mods':[],'language':'l_simp_chinese','native_boundary_month':118,'native_Q':20,'observed_monthly_step':8.5,'calendar_checkpoints':index['checkpoint_count'],'calendar_component_checks':index['component_checks'],'strict_stable_reload_checks':len(stable['checks']),'human_ACK_checks':len(human['checks']),'next_day_month_checks':len(checks),'final_error_bytes':len(error),'final_error_sha256':hashlib.sha256(error).hexdigest(),'error_scope':'21 inherited missing Workshop directories; no new errors during native setup/calendar/reload/ACK. Not global zero-error.','evidence':[{'file':f,'sha256':h.sha256(run/f)} for f in files],'scope':'True no-mod native Terravore Q20 endpoint, native random rewards, actual human completion UI, original-byte stable reload and no repeat next day/month; controlled source setup. Does not complete any deferred Mod civic route. All original failed assertions/UI attempts retained.'}
h.write_json(run/'postvanilla-native-boundary-complete-proof.json',proof);print(json.dumps({k:v for k,v in proof.items() if k!='evidence'}),flush=True)
print(json.dumps(h.stop(30)),flush=True)
