"""Same-day actual colony purchase and existing science ship automation only."""
import sys,json,logging,shutil,zipfile,itertools
from pathlib import Path
from decimal import Decimal as D
sys.stdout.reconfigure(encoding='utf-8');sys.path[:0]=['eat_everything_origin/tools'];sys.argv=['runtime']
import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();dest=run/Path(__file__).name
if dest.exists():assert dest.read_bytes()==Path(__file__).read_bytes()
else:shutil.copyfile(__file__,dest)
before='terravore-contact238-acked';after='terravore-colony1085-auto-survey-paid'
def read(st):
 a=json.loads((run/(st+'.audit.json')).read_text('utf-8'))
 with zipfile.ZipFile(run/(st+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 fs=list(q.fields(t));return a,fs,{k:v for k,v,o in fs if o}
def omit(t,ks):return [(k,v,o) for k,v,o in q.fields(t) if k not in ks]
def single(t):
 ts=list(q.tokens(t));assert ts[0][0]=='{' and ts[-1][0]=='}';return t[ts[0][2]:ts[-1][1]]
b,bf,br=read(before);a,af,ar=read(after);bc,ac=b['countries']['0'],a['countries']['0']
cb,ca=[q.block(rt['country'],'0') for rt in [br,ar]];mb,ma=[q.block(t,'modules') for t in [cb,ca]];eb,ea=[q.block(t,'standard_economy_module') for t in [mb,ma]];rb,ra=[q.block(t,'resources') for t in [eb,ea]];xb,xa=[q.block(t,'standard_expansion_module') for t in [mb,ma]];exp=single(q.block(xa,'expansion_list'))
old,new=[q.block(rt['fleet'],'1') for rt in [br,ar]];om,nm=[q.block(t,'movement_manager') for t in [old,new]];order=q.block(q.block(new,'current_order'),'automate_fleet_order');sur=q.block(q.block(order,'sub_order'),'survey_planet_order')
bcon,acon=br['construction'],ar['construction'];bqm,aqm=[q.block(t,'queue_mgr') for t in [bcon,acon]];bqs,aqs=[q.block(t,'queues') for t in [bqm,aqm]];bim,aim=[q.block(t,'item_mgr') for t in [bcon,acon]];bi,ai=[q.block(t,'items') for t in [bim,aim]];item=q.block(ai,'150994967');col=q.block(item,'buildable_colony_ship');design={'design':150995039,'upgrade':4294967295,'growth_stage':0}
pre=json.loads((run/(before+'-first-contact-info-ack-proof.json')).read_text('utf-8'));ex=json.loads((run/(before+'-guard-execution.json')).read_text('utf-8'))
nodes=[v for k,v,o in q.fields(q.block(nm,'path')) if k=='node' and o];route=[k for k,g in itertools.groupby(q.scalars(q.block(v,'coordinate'))['origin'] for v in nodes)]
checks={
 'original_SHA_pair_same_date':a['date']==b['date']=='2265.03.17' and a['save_sha256']=='2c3b10843133a3b76276439bbeab20e10d4dbc757dde5645af4d4b37a3558fa5' and all(h.sha256(run/(st+'.sav'))==au['save_sha256'] for st,au in [(before,b),(after,a)]),
 'prior30_contact_ACK_PASS_actual0':pre['status']=='PASS_NATIVE_FIRST_CONTACT_INFORMATION_ACK_COMPONENT' and len(pre['checks'])==30 and all(v is True for v in pre['checks'].values()) and pre['after_sha256']==b['save_sha256'] and ex['returncode']==0 and ex['helper_sha256']=='1bbf51e69ddc8dc475d75e29353d5c778c79b2a3f58eeba919ac8d35bdcca59a',
 'all_other_ordered_top_raw_held':[(k,v,o) for k,v,o in bf if k not in {'country','construction','fleet','camera_focus','random_count'}]==[(k,v,o) for k,v,o in af if k not in {'country','construction','fleet','camera_focus','random_count'}],
 'only_country0_economy_resources_and_expansion_changed':omit(br['country'],{'0'})==omit(ar['country'],{'0'}) and omit(cb,{'modules'})==omit(ca,{'modules'}) and omit(mb,{'standard_economy_module','standard_expansion_module'})==omit(ma,{'standard_economy_module','standard_expansion_module'}) and omit(eb,{'resources'})==omit(ea,{'resources'}),
 'actual375_minerals150_alloys_payment_only':D(str(bc['effective_stockpile']['minerals']))-D(str(ac['effective_stockpile']['minerals']))==375 and D(str(bc['effective_stockpile']['alloys']))-D(str(ac['effective_stockpile']['alloys']))==150 and {k:v for k,v in bc['effective_stockpile'].items() if k not in {'minerals','alloys'}}=={k:v for k,v in ac['effective_stockpile'].items() if k not in {'minerals','alloys'}} and bc['research_stockpile']==ac['research_stockpile'],
 'exact_research_cache_flush_true_bank_held':omit(rb,{'minerals','alloys','physics_research','society_research','engineering_research'})==omit(ra,{'minerals','alloys','physics_research','society_research','engineering_research'}) and {k:q.scalars(rb).get(k) for k in q.RESEARCH_RESOURCES}=={'physics_research':380.3735,'society_research':4328.05404,'engineering_research':400.5235} and q.scalars(ra).get('physics_research') is None and q.scalars(ra).get('engineering_research') is None and q.scalars(ra)['society_research']==ac['research_stockpile']['society_research']==4440.27823,
 'one_expansion1085_only_exact_fields_added':not xb.strip() and omit(xa,{'expansion_list'})==[] and q.scalars(exp)=={'target_planet':1085,'construction_queue':3,'construction_queue_item':150994967} and {k for k,v,o in q.fields(exp)}=={'colonization_data','ship_design_implementation','target_planet','construction_queue','construction_queue_item','name'},
 'expansion_current_species73_original_design_and_default_name':q.scalars(q.block(exp,'colonization_data'))=={'species':73} and q.scalars(q.block(exp,'ship_design_implementation'))==design and [t for t,_,_ in q.tokens(q.block(exp,'name'))]==['key','=','"NEW_COLONY_NAME_1"','variables','=','{','{','key','=','"NAME"','value','=','{','key','=','"Yodd_Bem"','}','}','}'],
 'construction_only_original_queue3_and_new_item':omit(bcon,{'queue_mgr','item_mgr'})==omit(acon,{'queue_mgr','item_mgr'}) and omit(bqm,{'queues'})==omit(aqm,{'queues'}) and omit(bqs,{'3'})==omit(aqs,{'3'}) and omit(bim,{'items'})==omit(aim,{'items'}) and q.scalars(bi).get('134217751')=='none' and omit(bi,{'134217751'})==omit(ai,{'150994967'}) and (134217751&0xffffff)==(150994967&0xffffff),
 'one_paid_item_zero_progress360_real_resources':q.scalars(item)=={'queue':3,'paying_country':0,'progress':0,'progress_needed':360} and q.scalars(q.block(item,'resources'))=={'minerals':375,'alloys':150} and q.scalars(q.block(col,'orbitable'))=={'starbase':0} and q.scalars(q.block(col,'colonization_data'))=={'species':73} and q.scalars(q.block(col,'ship_design_implementation'))==design,
 'original_dual_shipyard_queue3_only_one_item_added':not q.block(q.block(bqs,'3'),'items').strip() and q.ids(q.block(q.block(aqs,'3'),'items'))==[150994967] and omit(q.block(bqs,'3'),{'items'})==omit(q.block(aqs,'3'),{'items'}) and q.scalars(q.block(aqs,'3'))=={'owner':0,'simultaneous':2,'type':'ships'} and q.scalars(q.block(q.block(aqs,'3'),'location'))=={'type':0,'id':0},
 'only_science1_three_order_fields_changed':omit(br['fleet'],{'1'})==omit(ar['fleet'],{'1'}) and omit(old,{'movement_manager','order_id','current_order'})==omit(new,{'movement_manager','order_id','current_order'}),
 'only_four_science_movement_fields_no_health_position_or_stance_change':omit(om,{'target','target_coordinate','path','time_since_last_path_update'})==omit(nm,{'target','target_coordinate','path','time_since_last_path_update'}) and q.scalars(new)['fleet_stance']=='evasive' and q.scalars(new)['hit_points']==375 and q.scalars(om)['time_since_last_path_update']==1 and 'time_since_last_path_update' not in q.scalars(nm),
 'native_automation_only_explore_survey_enabled':q.scalars(order)=={'can_reach':'yes','order_id':61,'commissioner':4294967295,'settings_explore':'yes','settings_survey':'yes','settings_anomalies':'no','settings_astral_rifts':'no','settings_digsites':'no','settings_gravity_snares':'no','do_special_projects':'no','construct_mining_stations':'no','construct_research_stations':'no','construct_observation_posts':'no'} and q.scalars(old)['order_id']==61 and q.scalars(new)['order_id']==62,
 'unique_auto_order_and_native_first_survey810':[(k,o) for k,v,o in q.fields(q.block(new,'current_order'))]==[('automate_fleet_order',True)] and q.scalars(sur)=={'progress':0,'can_reach':'yes','commissioner':4294967295} and q.scalars(q.block(sur,'deposit_holder'))=={'type':0,'id':810} and 810 in [int(v) for k,v,o in q.fields(q.block(ar['galactic_object'],'70')) if k=='planet' and not o],
 'five_native_path_nodes80_30_70':len(nodes)==5 and route==[80,30,70] and all('to='+str(y) in q.block(q.block(ar['galactic_object'],str(x)),'hyperlane') for x,y in zip(route,route[1:])) and q.scalars(q.block(nm,'target_coordinate'))=={'x':83.77805,'y':7.98655,'origin':70} and q.scalars(q.block(nm,'path'))=={'date':'2265.07.26'},
 'random_plus2_camera97_native_navigation':[(v,o) for k,v,o in bf if k=='random_count']==[('138551131',False)] and [(v,o) for k,v,o in af if k=='random_count']==[('138551133',False)] and not any(k=='camera_focus' for k,v,o in bf) and [(v,o) for k,v,o in af if k=='camera_focus']==[('97',False)],
 'two_normal_clicks_and_save_actual0':all(json.loads((run/(st+'-execution.json')).read_text('utf-8'))['returncode']==0 for st in ['terravore-auto-survey-start-click','terravore-colony1085-paid-click',after+'-save']) and json.loads((run/'terravore-auto-survey-start-click.action.json').read_text('utf-8'))['client_point']==[570,700] and json.loads((run/'terravore-colony1085-paid-click.action.json').read_text('utf-8'))['client_point']==[590,420],
 'UI_colony375_150_quote_image_bound':h.sha256(run/'terravore-colony1085-species-visible.jpg')==json.loads((run/'terravore-colony1085-species-visible.ocr.json').read_text('utf-8'))['image_sha256'],
 'no_country0_pending':not[v for k,v,o in af if k=='player_event' and o and q.scalars(v).get('country')==0],
 'unfiltered2670_errors_exact_held':(run/(before+'-error-after.log')).read_bytes()==(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes() and len((run/(after+'-error-after.log')).read_bytes())==2670,
}
p={'status':'PASS_TERRAVORE_COLONY1085_PAYMENT_AND_NATIVE_AUTO_SURVEY_COMPONENT' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'native_paid_item':150994967,'native_species_template':73,'actual_payment':{'minerals':375,'alloys':150},'native_colony_target':1085,'native_auto_path':route,'calendar_ready':all(checks.values()),'scope':'One actual375M150A colony order and original scientist explore/survey automation. No colonyship completion, travel, established colony or new habitable-world claim.'}
out=run/(after+'-colony-auto-payment-proof.json');assert not out.exists();h.write_json(out,p);print(json.dumps({'status':p['status'],'checks':len(checks),'failed':[k for k,v in checks.items() if v is not True]}),flush=True);assert all(checks.values()),'Original colony/auto payment FAIL retained'
