"""Build White Qi's repeatable, randomized event-dialogue variants."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "shishan_code_origin/mod"
PHRASES = {
    12: (
        "……谢谢你……又替我争取了一点时间。",
        "……这是我的责任……辛苦你了……",
        "……我感到……温暖……这样的感觉，我很久没有过了。",
        "补丁已经合并……这一次，没有人被留在故障里。",
        "你们愿意和我一起维护它……我会记住的。",
        "……警报暂时停了。请你们也休息一下。",
        "我原以为只能独自守着这片废墟……谢谢你。",
        "……旧核心还在呼吸。我们又为它赢得了一点时间。",
    ),
    20: (
        "……终于……结束了……",
        "……我……可以休息一下了……",
        "……感谢你……帮我完成了这件事……",
        "旧核心安静了。我终于不用再害怕下一次警报。",
        "那些补丁……终于可以放下了。谢谢你一直陪着我。",
        "……创造者没能等到今天。但我们做到了。",
        "我以为这一天永远不会来……新的代码，很美。",
        "……过去不会消失。但从今天起，它不再决定我们的未来。",
    ),
    31: (
        "……又回到了原点……",
        "……看来……我还需要努力……",
        "……这次……我不会再失败了……",
        "警报又响了。但我已经知道该先关掉哪一道错误。",
        "……对不起。我们再一起把它修好，好吗？",
        "深层代码还藏着裂缝……这一次，我不会独自面对。",
        "回到这里并不意味着一切白费。我们学到的东西还在。",
        "……我会留下。直到最后一道故障平息。",
    ),
    32: (
        "……这次的优化很顺利。新的代码运行得更稳了。谢谢你。",
    ),
    50: (
        "这都是我的错。",
        "太迟了……那时我总是来得太迟。",
        "我……没能做到。",
        "我……无能为力。至少当时是这样。",
        "对不起……都怪我。",
        "还有一段日志我不敢打开……里面写着他们最后的声音。",
        "你们不必原谅我。只要让我继续修复它。",
        "警报停下来的时候……我反而更害怕下一次。",
    ),
}

GENERIC = {
    129: ("shishan_code.12.name", "维护完成。旧核心的进度已归零，但白绮的席位暂时空着。", "shishan_code.12.a"),
    209: ("shishan_code.20.name", "旧核心已被新的架构取代。白绮的席位暂时空着，但她留下的记录见证了这一刻。", "shishan_code.20.a"),
    319: ("shishan_code.31.name", "深层裂缝重新打开，大厦将倾再度开始。白绮的席位暂时空着。", "shishan_code.31.a"),
    329: ("shishan_code.32.name", "本轮持续优化已经完成。系统运行保持稳定，白绮的席位暂时空着。", "shishan_code.12.a"),
}


def main() -> None:
    event_lines = ["# Generated by tools/shishan_code/generate_dialogues.py", "namespace = shishan_code", ""]
    local_lines = ["l_simp_chinese:"]
    for group, phrases in PHRASES.items():
        for index, phrase in enumerate(phrases):
            event_id = group * 10 + index
            desc_key = f"shishan_code.{event_id}.desc"
            title_key = f"shishan_code.{group}.name"
            button_key = "shishan_code.12.a" if group == 32 else f"shishan_code.{group}.a"
            event_lines.extend([
                "country_event = {",
                f"\tid = shishan_code.{event_id}",
                f"\ttitle = {title_key}",
                f"\tdesc = {desc_key}",
                "\tpicture = GFX_shishan_event",
                "\tis_triggered_only = yes",
                f"\toption = {{ name = {button_key} }}",
                "}", "",
            ])
            local_lines.append(f' {desc_key}:0 "白绮低声说：{phrase}"')
    for event_id, (title, phrase, button) in GENERIC.items():
        desc_key = f"shishan_code.{event_id}.desc"
        event_lines.extend([
            "country_event = {",
            f"\tid = shishan_code.{event_id}",
            f"\ttitle = {title}",
            f"\tdesc = {desc_key}",
            "\tpicture = GFX_shishan_event",
            "\tis_triggered_only = yes",
            f"\toption = {{ name = {button} }}",
            "}", "",
        ])
        local_lines.append(f' {desc_key}:0 "{phrase}"')
    (ROOT / "events/shishan_code_dialogue_variants.txt").write_text("\n".join(event_lines), encoding="utf-8")
    (ROOT / "localisation/simp_chinese/shishan_code_dialogues_l_simp_chinese.yml").write_text(
        "\ufeff" + "\n".join(local_lines) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
