"""Exact native reload cache supplement, original strict24 FAIL retained."""
import json,logging,shutil,sys,zipfile,re
from decimal import Decimal as D
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,'eat_everything_origin/tools');sys.argv=['runtime'];import runtime as r,audit_save as q
logging.disable(logging.INFO);h=r.harness;run,user,m=h.load_run();shutil.copyfile(__file__,run/Path(__file__).name);readj=lambda p:json.loads(p.read_text('utf-8'))
before='terravore-ascension-capital-paid';after='terravore-ascension-capital-resumed';b=readj(run/(before+'.audit.json'));a=readj(run/(after+'.audit.json'));old=readj(run/(after+'-proof.json'));control=Path('eat_everything_origin/docs/evidence/priority-terravore-progress-2026-10-09/native-coordinator-capital-payment-error-control');v=readj(control/'coordinator-control-paid.audit.json');vp=readj(control/'coordinator-control-paid-error-proof.json');attr=readj(run/(before+'-native-coordinator-error-supplement.json'))
bc,ac=b['countries']['0'],a['countries']['0'];bb,ab=bc['budget'],ac['budget'];bh,ah=q.block(bb,'income_high_water_mark'),q.block(ab,'income_high_water_mark');omit=lambda t,ks:[(k,v,o) for k,v,o in q.fields(t) if k not in ks]
income={('trade_policy', 'trade'): (51.3169, 51.39224), ('planet_jobs', 'unity'): (0.38907, 0.38913), ('planet_miners', 'minerals'): (114.1168, 114.1352), ('planet_technician', 'energy'): (87.3126, 87.3264), ('planet_bureaucrats', 'unity'): (62.85048, 62.85972), ('planet_metallurgists', 'alloys'): (20.0541, 20.0574), ('planet_traders', 'trade'): (15.25128, 15.25392), ('planet_maintenance_drones', 'trade'): (36.09469, 36.17721), ('planet_physicists', 'physics_research'): (6.86307, 6.86426), ('planet_biologists', 'society_research'): (6.86307, 6.86426), ('planet_engineers', 'engineering_research'): (6.86307, 6.86426)}
expenses={('planet_resource_deficit', 'trade'): (0.02907, 0.03889), ('trade_policy', 'trade'): (51.3169, 51.39224), ('planet_pop_assemblers', 'minerals'): (4.3307, 4.3318), ('planet_bureaucrats', 'energy'): (24.25192, 24.25808), ('planet_bureaucrats', 'minerals'): (24.25192, 24.25808), ('planet_metallurgists', 'minerals'): (25.9842, 25.9908), ('planet_traders', 'minerals'): (3.46456, 3.46544), ('planet_physicists', 'minerals'): (6.2362, 6.23779), ('planet_biologists', 'minerals'): (6.2362, 6.23779), ('planet_engineers', 'minerals'): (6.2362, 6.23779), ('planet_pops_traits', 'minerals'): (77.688, 77.742)}

def flat(d):return {(k,x):v for k,values in d.items() for x,v in values.items()}
def exact_cells(kind,expected):
 x,y=[flat(c['budget_categories']['current_month'][kind]) for c in [bc,ac]]
 return set(x)==set(y) and {(k):(x[k],y[k]) for k in x if x[k]!=y[k]}==expected
cur=ac['budget_categories']['current_month'];inc,exp,bal=[flat(cur[k]) for k in ['income','expenses','balance']];balances_ok=all(abs(D(str(inc.get(k,0)))-D(str(exp.get(k,0)))-D(str(bal.get(k,0))))<=D('.00002') for k in set(inc)|set(exp)|set(bal));hw=q.scalars(q.block(ah,'current'));highwater_ok=all(abs(D(str(hw.get(k,0)))-max(D(str(q.scalars(q.block(bh,'current')).get(k,0))),sum((D(str(values.get(k,0))) for values in cur['income'].values()),D(0))))<=D('.00002') for k in set(hw)|{k for values in cur['income'].values() for k in values})
ca={'amenities': (16567.1216, 16593.19104), 'crime': (17.88, 17.94), 'free_amenities': (11143.9216, 11169.99104), 'free_housing': (1835.5, 1832), 'housing_usage': (8632, 8638), 'total_housing': (10467.5, 10470)}
colonies_ok=set(b['colonies'])==set(a['colonies']) and all(({k:v for k,v in c.items() if k not in ca}=={k:v for k,v in a['colonies'][i].items() if k not in ca} and all((c[k],a['colonies'][i][k])==values for k,values in ca.items())) if i=='0' else (c.get('binary_flags') is None and a['colonies'][i].get('binary_flags')==24 and {k:v for k,v in c.items() if k!='binary_flags'}=={k:v for k,v in a['colonies'][i].items() if k!='binary_flags'} and c['actual_pop_sum']==a['colonies'][i]['actual_pop_sum']==0) if i in ['15','24'] else c==a['colonies'][i] for i,c in b['colonies'].items())
planets_ok=set(b['planets'])==set(a['planets']) and all(({k:v for k,v in p.items() if k!='carrier_binary_flags'}=={k:v for k,v in a['planets'][i].items() if k!='carrier_binary_flags'} and p['carrier_binary_flags']==1 and a['planets'][i]['carrier_binary_flags']==3) if i=='7' else p==a['planets'][i] for i,p in b['planets'].items())
def raw(st):
 with zipfile.ZipFile(run/(st+'.sav')) as z:t=z.read('gamestate').decode('utf-8-sig')
 return {k:v for k,v,o in q.fields(t) if o}
br,ar=raw(before),raw(after);af={k:v for k,v,o in q.fields(ar['fleet']) if o};ships={k:v for k,v,o in q.fields(ar['ships']) if o};owned=re.findall(r'\bfleet\s*=\s*(\d+)',q.block(q.block(q.block(ar['country'],'0'),'fleets_manager'),'owned_fleets'));actual=[s for fid in owned if q.scalars(af[fid])['ship_class']=='shipclass_military' for s in q.ids(q.block(af[fid],'ships'))]
checks={'original24_exact_three_FAIL_other21_true':old['status']=='FAIL' and len(old['checks'])==24 and [k for k,v in old['checks'].items() if not v]==['budget_held','colonies_held','planets_held'] and readj(run/'coordinator-production-resume-load-execution.json')['returncode']==1,'production_original_SHA_pair_same_date':h.sha256(run/(before+'.sav'))==old['before_sha256']==b['save_sha256'] and h.sha256(run/(after+'.sav'))==old['after_sha256']==a['save_sha256'] and a['date']==b['date']=='2238.10.02','bound_native_error_attribution11_PASS':attr['status']=='PASS_SCOPED_NATIVE_COORDINATOR_ERROR_ATTRIBUTION' and len(attr['checks'])==11 and all(attr['checks'].values()) and attr['after_sha256']==b['save_sha256'],'bound_no_mod_paid33_PASS_same_original_source':vp['status']=='PASS_COORDINATOR_CONTROL_LOAD_ONLY' and all(vp['checks'].values()) and len(vp['checks'])==33 and h.sha256(control/'coordinator-control-paid.sav')==vp['after_sha256']==v['save_sha256'] and readj(control/'manifest.json')['original_seed']['sha256']=='4371182e222afb2b0ad278c0b1e06f8b767ac28049ad39d1edccf6f6e10b6214' and readj(control/'coordinator-control-error-guard-execution.json')['returncode']==0,'exact_colony_cache_changes_only':colonies_ok,'entire_colonies_equal_independent_empty_mod_reload':a['colonies']==v['colonies'],'exact_planet_core_carrier1_to3_only':planets_ok and v['planets']['7']['carrier_binary_flags']==3,'budget_outside_current_highwater_raw_held':omit(bb,{'current_month','income_high_water_mark'})==omit(ab,{'current_month','income_high_water_mark'}),'exact_predeclared_income_expense_cache_cells':exact_cells('income',income) and exact_cells('expenses',expenses),'new_balance_each_category_income_minus_expense':balances_ok,'highwater_length4_to5_other_fields_held_current_max_income':q.scalars(bh)['length']==4 and q.scalars(ah)['length']==5 and omit(bh,{'length','current'})==omit(ah,{'length','current'}) and highwater_ok,'population_actual8638_cached_upkeep_updates_only':b['colonies']['0']['actual_pop_sum']==a['colonies']['0']['actual_pop_sum']==8638 and all(D(str(c['budget_categories']['current_month']['expenses']['planet_pops_traits']['minerals']))==D(str(co['colonies']['0']['housing_usage']))*D('.009') for c,co in [(bc,b),(ac,a)]),'actual19_paid_ships_design_full_hull_and_unchanged_construction':len(actual)==len(set(actual))==19 and all(q.scalars(ships[str(s)])['hitpoints']==250 and q.scalars(q.block(ships[str(s)],'ship_design_implementation'))['design']==67110548 for s in actual) and br['construction']==ar['construction'] and br['zones']==ar['zones'] and br['buildings']==ar['buildings'],'fresh_unfiltered_logs_2670_held':(run/(after+'-error-before.log')).read_bytes()==(run/(after+'-error-after.log')).read_bytes() and len((run/(after+'-error-after.log')).read_bytes())==2670}
p={'status':'PASS_SCOPED_COORDINATOR_PRODUCTION_RESUME_COMPONENT' if all(checks.values()) else 'FAIL','checks':checks,'before_sha256':b['save_sha256'],'after_sha256':a['save_sha256'],'income_changes':{str(k):v for k,v in income.items()},'expense_changes':{str(k):v for k,v in expenses.items()},'actual_current_month_nets':{k:sum(v.get(k,0) for v in cur['balance'].values()) for k in ['energy','minerals','alloys','unity','trade']},'actual_ship_ids':actual,'scope':'21 original valid state checks plus exact scoped reload caches, entire colony audit equal independent no-mod load; valid native budget balances/highwater and unchanged paid upgrade construction, zones/buildings, no actual inventory/reward change. Original strict24 FAIL retained, no general cache root-cause or full-route claim.'};out=run/(after+'-resume-supplement.json');assert not out.exists();h.write_json(out,p);print(json.dumps(p),flush=True);assert all(checks.values()),'Original resume supplement FAIL retained'
